### ISSUE TITLE
[dev.icinga.com #6871] multi-parent dependencies

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#1869]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6871

**Created by 9er on 2014-08-07 10:58:06 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2014-11-24 14:16:32 +00:00_)
Target Version: _Backlog_
Last Update: _2016-11-28 12:09:11 +00:00 (in Redmine)_

---

Problem:
- hosts might have 2 parents (for redundancy), e.g., servers with uplinks to 2 routers and BGP failover
- adding a dependency for each parent causes notifications to be disabled if just one parent is down and the host is still reachable
- notifications should be disabled only if both parents are down and the host is unreachable

Config could look something like this:

    object Dependency "server-routers" {
      parent_host_name = [ "router1", "router2" ]

      child_host_name = "server"
    }

Maybe even add an option to decide, whether all parents must be down ("AND") or just one ("OR"). The "OR" option can then be used to summarize multiple single dependencies.

    object Dependency "server-routers" {
      parent_host_name = [ "router1", "router2" ]
      child_host_name = "server"

      operation = "AND"
    }

---

**Relations**:

* relates [#6871](https://dev.icinga.com/issues/6871)
* duplicates [#6871](https://dev.icinga.com/issues/6871)
* duplicates [#6871](https://dev.icinga.com/issues/6871)

**Comment by Duffkess** [comment]
Hi all toghether, I just came from monitoring-portal.com.
I just read everything you posted here and I am thinking of what the purpose of the OR operator is here?
I cant think of a situation where I would like to define multiple dependencies for a host where one failing parent would mean the child is unavailable. 
This might be good for services where one service is depending on all parent services, but therefor it would be better to use buisness procccess right?
So why not always use AND as the default parameter? Do you have any idea on where this feature (somehow) could be useable in a stable release?
I definitly need this feature, that why I currently think about a quick dirty trick and write a script combined with db querys and api calls that does the trick for me..
Thank you for any details!

**Comment by lesinigo** [comment]
@Duffkess I too can't think of a situation where the "OR unreachability" logic makes sense, but I never asked to simply change it to AND because it is the current Icinga2 functionality and there can be someone out there who is actually using it. A flag to switch between `AND` and `OR` _shouldn't_ be too hard to add and you can just set it to _your_ preferred default in something like the `generic-host` template.

@ icinga devs: I briefly talked about this issue with @gethash during the last Puppetconf, is there anything (as in _"anything but C/C++ code"_ 😂) we can do to help this move along?

**Comment by dnsmichi** [comment]
There isn't any technical concept or specification available. We are not doing anything here, unless someone considers sponsoring this feature.

**Comment by odeshog** [comment]
@dnsmichi The OP provided a concept, and I do not see what is wrong with that. Perhaps you can clarify? 
The suggestion was, to the best of my understanding, to save a parameter on the Dependency objects telling what boolean operation (default OR) to use when an object has multiple parents. The configuration could be applied like:

```
apply Dependency "Parents" for (parent in host.vars.parents) to Host {

    parent_host_name = parent
    operator = "AND"
    assign where host.vars.parents
    
}
```

You commented before on the OP's suggestion that:

> Applying Dependency objects with different types and multiple ones - not a clear result set. 2) Put on dependency objects themselves - how to know how many other dependencies will be generated from apply rules?

I'm not sure I understand this comment (maybe it no longer applies), but the configured operator would apply for the specified dependency (i.e. "Parents" here).

**Comment by dnsmichi** [comment]
Summary of the issue below.

# Proposals

## Arrays

The OP proposal won't work for service parents.

```
parent_host_name = [ "router1", "router2" ]
parent_service_name = [ "port1", "port2" ]
```

There is no indication which service parent objects could be specified. 

## AND operator

Dependencies are objects generated from apply rules. They also may co-exist written on their own.

In the end, everything looks like this

```
object Dependency "router1-dep1" {
  parent_host_name = "router1"
  ..
}

object Dependency "router2-dep2" {
  parent_host_name = "router2"
...
}
```

You would need to glue them together. Still, where would you do that? In side "router-dep1" ... or "router-dep2" .. or both? That allows for inconsistent configuration and makes it hard to troubleshoot. Especially if both Dependency objects exist in different file locations.

If you are putting such into an Apply rule (normal, or a for loop), this could somehow "generate" the logical AND or OR relation between generated dependency objects. This is different to everything else known from apply rules, just a specific idea for Dependency logic. Hard to explain, hard to document, and nothing one would like to maintain or support. 

# General Ideas

Since Dependency objects are just generated from apply rules, one would need to find a way to "glue" them together.

Or, to glue parent objects and their state together. This is what this is all about - if the conditions 

- one or the other is fine, be OK
- both are down, be NOT-OK

are fulfilled, dependency logic kicks in as you are used to it currently.

Icinga 2 should know upon reachability calculation, that an object has multiple parents, and how they relate together. Or how to fetch the overall state from the parents objects, and which rules to apply on them.

## Multiple parents with different AND/OR/etc. relationship

One thing to keep in mind while designing this: Multiple parents mean 2, 3, or 10 or n parent objects combined with a logical operator.

Should it always be `dep1 && dep2 && dep3` or would one like to have `dep1 && dep3 || dep 2` for example?

This needs to be considered before adding this feature, to avoid possible feature requests and have yet another hardcoded solution. 


# Other solutions

## Businessprocess as virtual parent object

Have a business process configuration which deals with the parent host's overall state. It considers the state from its own defined logic and expression language. This requires the businessprocess module for Icinga Web 2 and its icingacli component. CheckCommands in the ITL do exist.

## Virtual parent object with object accessor functions

Define a dummy host or service which calculates the runtime state via Icinga 2 DSL, similar to the cluster check example from the docs.

# Conclusion

Most likely a rule based language addition which is evaluated after all configuration objects are loaded, is the best addition here. This requires the implementation of #3520 in a certain way, and some specific sets and rules one can use. This could also involve functions which retrieve parent trees and modify such after.

It may also be reasonable to take virtual hosts/services into account, which combine specific "parent" states required for the described scenarios.

I wouldn't change anything in the "parent_host_name" and "parent_service_name" attributes, as backends like databases rely on the name and relationship between objects. So does anything which queries Icinga 2 data.

**The key point is configuration here, and how to handle the algorithm.** I think we all agree on this.

That's my 2 cents on the matter. If you agree on the ideas, or have any other proposals which help here, feel free to suggest/sponsor.

**Comment by mdetrano** [comment]
Another suggestion, perhaps simpler, though more specific:

Just have a "reachability" field for Dependencies.  If its set true, then it is considered together with any other applicable dependency that has "reachability" set true.  The dependency only fails when ALL reachability-tagged dependencies fail.

**Comment by odeshog** [comment]
@dnsmichi Thank you for the summary, that's very helpful! A comment on "glueing" the dependencies: That could perhaps be done based on grouping the children (child_service_name and child_host_name) with some other attribute of the dependency object. The reachability of the child is then calculated from the combined state of all parents in the group using the configured operation (with no mixing).
The "other" attribute to group by could be a new parameter or, with some modifications, the name of the dependency (by which I mean the name as given in config files, let's call it short_name). 
Let me explain what I mean by modifications and do correct me if I'm wrong, but I believe that currently when you configure a dependency, an object is created as:

`child_host_name!short_name`

or if child_service_name exists

`child_host_name!child_service_name!short_name`

In the case of apply rules (at least for Hosts), some magic is performed and the parent_host_name is concatenated with short_name (I assume to avoid duplicate objects). If all dependency objects would be created as

`child_host_name!child_service_name!short_name!parent_host_name`

this problem would be allieviated and configuration (at least to my eyes) be more consistent. parent_host_name is anyway mandatory for a dependency so perhaps(?) this change would be acceptable.
I understand your concern about future feature requests regarding how to combine parent states and I do not have a suggestion here. From previous comments in the thread and my own use case, the most important thing seems to be able to configure a single operation to use for all parents.

**Comment by widhalmt** [comment]
How about changing how multiple single dependencies work? Switch from AND to OR?
So, if I have host a which I can reach via two redundant routers b and c and I create a dependency so a is dependent from b and another dependency so a is dependent from c. Current versions will show a unreachable if either b or c go down.
Couldn't we just change the behaviour that a is reachable when at least b or c is up?
I know this wouldn't satisfy all needs but I'm quite positive there are a lot more users that want it the other way round from what it is now.

**Comment by cjsoftuk** [comment]
Reading through this I can see why the devs are quite averse to any of the above.  The language of the configuration and the way that dependencies can be applied means that a host has no idea what services, dependencies, etc might be applied to it, thus making it the wrong place to define how the logic for those dependencies should be applied.

Similarly, you can't define AND/OR this in the dependency because you don't know how to group the dependencies.

However: I think there's a way to implement the latter that isn't too painful.  It does rely on people being sensible with the "priority" field.

1. Add a "priority" and "logical_operator" field to the Dependency structure.
2. Enforce that, for a given priority, logical_operator must be the same.
3. Use priority and logical_operator to generate availability logic for the child host (enclosing each priority in brackets to group together).

Here's a worked example:

If I defined, for example (and I'm doing this very early morning from memory - not had any coffee yet!):
```
object Host "router-a" { 
...
}
object Host "router-b" { 
...
}

object Host "host-a" {
...
}

apply Dependency "host-a-on-routers" to Host {
    child_host_name = "host-a"
    priority = 1
    logical_operator = "OR"
    assign where match("router-*", host.name)
}
```

This would generate an 'availability expression' for host-a of (router-a || router-b).

Where "priority" and "logical_operator" are left undefined, "logical_operator" would default to "AND" (as it currently does).  Priority would default to (say) 100 to ensure all user defined logic takes precedence.  The 'availability expression' would be build with priority 0 first, going all the way up to, say, priority 255.

Under this scheme, if you want to apply OR-based logic you must define priority and the logical_operator to be OR.

How does this sound to the developers?  I'm sure I've missed something here - but I can't immediately see it.

If the developers see merit in this as a potential solution, I am happy to try and find some time to start putting together some patches.

**Comment by odeshog** [comment]
I'm not sure I follow what you intend with priority, are you proposing that only the lowest priority is checked? Or what do you mean by user-defined logic takes precedence?

**Comment by cjsoftuk** [comment]
@odeshog - So... Priority would be to do with the order in which groups are ANDed together

Let me extend my (fictional) example:

Host A depends on one of router-a or router-b and one of router-c and router-d being up.

```
object Host "router-a" { 
...
}
object Host "router-b" { 
...
}

object Host "router-c" {
...
}

object Host "router-d" {
...
}

object Host "host-a" {
...
}

apply Dependency "host-a-on-min-router-ab" to Host {
    child_host_name = "host-a"
    priority = 1
    logical_operator = "OR"
    assign where match("router-(a|b)", host.name)
}

apply Dependency "host-a-on-min-router-cd" to Host {
    child_host_name = "host-a"
    priority = 2
    logical_operator = "OR"
    assign where match("router-(c|d)", host.name)
}
```

With what I am proposing, I would expect the availability logic to generate the following boolean expression for reachability of host-a

`(router-a || router-b) && (router-c || router-d)`

Priority 1 entry was anded with the priority 2 entry (which is then anded with any higher number priority entries).

It allows relatively complex expressions.  I think the only one that proves a problem is (w && x) || (y && z) - but I'm fairly sure you could rewrite that a different way.

Does that explain what I was on about

**Comment by odeshog** [comment]
@cjsoftuk thank you, that's very clear now. Functionally this is what I, and pretty much every other user in this thread, want. I would only suggest some more descriptive name instead of priority, dependency_group perhaps.

**Comment by cjsoftuk** [comment]
@odeshog - Agreed - perhaps wrong name.  Was about half 7 in the morning when I wrote that having not fully woken up!

I am interested to hear what the core developers think when they get some time to assess this.  I definitely have a bunch of use cases where "and" is completely the wrong operator.

**Comment by log1-c** [comment]
After reading/skipping through this and reading @dnsmichi https://github.com/Icinga/icinga2/issues/1869#issuecomment-343167646 to the thread an idea came to my mind, regarding the "virtual parent object".

Though this might just be applicable to host dependencies:
Why not create a host object that uses check_multi as check command and checks the IPs of your various hosts you want to have as parent. As long as one of the IPs answers the dependencies is fullfilled.

This is, I think, a valid workaround until the "big issue" gets tackled.

**Comment by efuss** [comment]
I think there's a rather easy and straightforward solution to the problem.

First: There seems to be some confusion regarding what an _and_ resp. _or_ operator is supposed to mean: Is the dependency OK when A and B are OK or is the dependency violated only if A and B are not OK. I propose to use the terms _cumulative dependency_ and _redundant dependency_ instead.

The main pont is that any boolean expression can be expressed as a single _and_ of several _or_'s of the input variables and their negations (or as a single _or_ of several _and_'s of them).

We already have one of the logical operators as several distinct `Dependency` Objects are interpreted to be cumulative.

We already have a notion of negation since a `Dependency` Object's `states` attribute can be set arbitrarily.

So the only thing missing is a way to express redundant dependencies. If we introduce a syntax to list several parents in one `Dependency` Object which are then interpreted to be redundant, we're done.

A possible syntax would be an array of dictionaries, i.e.
```
parents = [
	{
		host = "host1"
		service = "service1"
		states = [ OK, Warning ]
	}
	{
		host = "host2"
		service = "service2"
		states = [ Critical, Unknown ]
	}
]
```
You could probably introduce some short-cuts, like
```
parents = [
	{
		hosts = [ "host1", "host2" ]
		service = "service"
	}
]
```
(and `host`/`services`).
One could even take
```
parents = [
	{
		hosts = [ "host1", "host2" ]
		services = [ "service1", "service2" ]
	}
]
```
to mean all four combinations of hosts and services.

Or you revert to writing down the expression explicitly in a syntax like
`parents = "host1!service1[OK,Warning] || ( host2!service2 && host3!service3)"`

**Comment by dnsmichi** [comment]
```
parents = [
	{
		hosts = [ "host1", "host2" ]
		services = [ "service1", "service2" ]
	}
]
```

brings back the confusion which objects are actually attached to each other. All? Some? I've mentioned such in https://github.com/Icinga/icinga2/issues/1869#issuecomment-343167646

In terms of a behavioural change, is your desire to control the behaviour of multi-parent dependencies in a global fashion, or on a per object basis? https://github.com/Icinga/icinga2/issues/1869#issuecomment-351703502 from @widhalmt  implies that.

**Comment by efuss** [comment]
I don't quite get why you focus on a possible special case of a proposed possible short-cut instead of commenting the overall concept (distinct `Dependency` Objects cumulative as-is, additional syntax for redundancy-type parents within a single `Dependency` Object).

As I wrote, In that special case I would expect all four combinations.

As I wrote, I don't intend to change the global behaviour of multiple distinct dependencies, which must remain cumulative because that's normally what one needs: SSH login is not supposed if the server is down; it also allowed to fail if name resolution doesn't work; it may fail because LDAP is down, etc.

In my application, I normally need the cumulative type. However, in some cases (which reflect redundant services), I need the redundancy type: name resolution is not supposed to work if all configured resolvers are down; ntpd is not supposed to be happy with it's peers if all primary ntp servers are down etc.

**Comment by dnsmichi** [comment]
I'm not in the mood to argue about who said what and why, but look for a possible solution which satisfies the majority.

So to speak, @widhalmt could live with a global configuration option changing the global behaviour.  That's fairly easy to implement although I'm not a friend of such config options. @efuss wants to configure it on a per object level, which still needs a better configuration specification.

Is there a common sense amongst others contributing to this issue?

- [ ] global option
- [ ] per object

**Comment by dgoetz** [comment]
- [x] global option
- [ ] per object

For me a global option would be enough as I commonly need only the logic for redundant dependencies like two switches and the servers behind should be unreachable if both are down or virtualization hosts and the virtual machines should be unreachable if the hosts are down.

**Comment by efuss** [comment]
I agree that a global option is a bad idea. It's confusing and I guess nobody can live with all dependencies being interpreted as redundant (you certainly don't want the implicit dependency of a `Service` on it's `Host` and other explicit dependencies being regarded as redundancy-type).

My typical scenario is that a server process needs, say, LDAP and name resolution to work and I have two LDAP servers and two resolvers. I need to be able to express that. The easiest and most straightforward solution I can think of is to apply some „needs LDAP“ dependency to all services requiring LDAP lookups and, in that `Dependency` Object, write something like

```
parents = [
	{
		host = "ldap-primary"
		service = "ldap"
	}
	{
		host = "ldap-backup"
		service = "ldap"
	}
]
```

where the `parents` array's elements are interpreted as redundant options.
 Add a „need resolv“ dependency for `Service` Objects dependent on name resolution, have both dependencies interpreted cumulative (as-is) and, in my opinion, you're done, no?

Do you find that not covering people's needs, being confusing, over-engeneerd or difficult to implement?

**Comment by dnsmichi** [comment]
It is a mix of both - confusing and likely users may not understand it, or implement it the wrong way. I know that you could live with your proposal, but you're not the one maintaining all the features and doing support and documentation for them - no offence here.

Probably the array with dictionary notation is the best proposal so far. Still, how would such an array be dealt with - is it `AND` or is it `OR`. One should be able to tell just by looking at the config snippet.

For the implementation parts, one needs to consider that such dependencies are not available in the IDO backend, might be hard to traverse that via REST API too. Not so easy, and should be taken into account when creating a new backend, FYI @lippserd 

Either way, I'd still like to hear what others in this issue think about

```
- [ ] global option
- [ ] per object
```

**Comment by dgoetz** [comment]
Perhaps what I forgot to mention is my use of the businessprocess addon for more complicated dependency requirements which can also solve things like requiring two out of five webservers. Having such things in the core could be helpful, but I am fine with having them somewhere else and an simple solution in the core.

**Comment by dnsmichi** [comment]
One implementation "detail" to consider: Right on, object relations need to be tracked, e.g. for the REST API joins. Such a thing won't be possible with a `parents` array, nor could it be dumped to the database backend easily. 

https://github.com/Icinga/icinga2/blob/master/lib/icinga/dependency.ti#L70

I'm thinking about a different method, like grouping these dependencies and evaluating them based on a specified operator. This wouldn't change anything with the current Dependency configuration objects, and introduce an optional element. It also can re-use the group assign where logic, and copy the group membership resolving.

Let's see about that, right on I have some bugs for 2.9 prior to looking into this again.

**Comment by dnsmichi** [comment]
@htriem has joined the Icinga 2 core team a while ago with now taking more maintainer responsibilities.

During the issue grooming we had some weeks ago, his exercise was determine the question and solutions in this issue. Also, a special exercise was to weigh the issue in terms of config option vs. change the behavior. Without any influence by myself who has no clear view on the issue anymore.

This is what @htriem achieved (at the very moment he's on vacation, therefore I am writing this now):

1) We couldn't find a reliable scenario where the current behavior with the "if one dependency fails, mark this unreachable" would apply.
2) The topic contains 20 thumbs up and responses to change the behavior, with only developers wanting to keep the current behavior. That's a fair point to take into account.
3) The proposed configuration options are either too complicated, or they do not fit the current DSL approach with "there's only one way to do it right" and "keep it simple, stupid".
4) During the grooming session, an actual patch was implemented in #7785 to change the behavior.

A small bug with "no dependencies -> be reachable" existed, which was unveiled with our unit tests yesterday. Already fixed. 

I've added some more unit tests in #7785 rendering this change "bullet proof".

**Comment by efuss** [comment]
I'm unhappy with this change because it can lead to unrelated services being regarded as redundant wrt. to each other. It can even make a host being regarded as redundant wrt. to a service.

For example (unfortunately, I didn't think about this in the discussion and stumbled over it only after upgrading to 2.12.0), applying the the explicit [disable-host-service-checks](https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#implicit-dependencies-for-services-on-host) dependency described in the [Monitoring Basics](https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/) chapter will defeat all other dependencies.

My original dictionary idea seems to be too complicated.

I then came up with the idea to introduce an `essential` attribute for Dependency Objects, meaning that dependency alone will make the parent unreachable. I implemented this, but after that came up with still another idea.

What about a new `redundancy_group` attribute for dependencies?
Specifying a `redundancy_group` would cause a dependency to be regarded as redundant only inside that redundancy group, e.g., "routers".
Dependencies lacking a redundancy_group attribute would be regarded as essential for the parent.

This would, with only one additional simple string attribute, allow for both cumulative and redundant dependencies and even a combination (cumulation of redundancies, like SSH depending on both LDAP and DNS to function, while operating redundant LDAP servers as well as redundant DNS resolvers).

I've implemented this in https://github.com/Icinga/icinga2/pull/8218 and it appears to work. I can't tell whether the additional `std::unordered_map` computations in `Checkable::IsReachable()` are tolerable for huge installations.

I also don't feel comfortable enough with the test framework to integrate unit tests for the proposal. The current tests are, of course, expected to fail with the change.

**Comment by efuss** [comment]
I received a mail `PR run failed: Packages - Introduce redundancy groups for Dependency Objects (3b10401)` that I don't understand.

In the reports, I see some "Job canceled" messages plus `Error: Transaction test error:
1181
  file /usr/include/mysql/mariadb_rpl.h conflicts between attempted installs of mariadb-devel-3:10.3.22-1.fc31.x86_64 and mariadb-connector-c-devel-3.1.9-5.fc31.x86_64`

I don't think my patch broke that.
