### ISSUE TITLE
[dev.icinga.com #9873] Add option to Windows installer to add global zone during setup

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3245]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9873

**Created by twidhalm on 2015-08-11 09:06:35 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-18 14:07:23 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi!

It would be nice to add global zones (with configurable name) during the graphical installation of the Windows installer so the agent gets the complete configuration set synchronized during install.

Cheers,
Thomas

---

**Relations**:

* relates [#10120](https://dev.icinga.com/issues/10120)

**Comment by dnsmichi** [comment]
Not so relevant anymore with 2.7.0 and default global zones.

**Comment by dgoetz** [comment]
I think it is still relevant as you do not want all agents to reload for example when a user is created so for my setups I do not keep "director-global" on agents and use instead something like "linux-agents" and "windows-agents" which only contains relevant CheckCommands.

**Comment by dnsmichi** [comment]
Kindly ask @mwaldmueller to add it to the wishlist then.

**Comment by mcktr** [comment]
I think this is not limited to Windows, adding global zones during the node wizard/node setup would be nice on Linux too. 

My proposal: Adding an option to node wizard/node setup to set global zones. When the node setup provides such an option, the Windows installer could use them to add the global zones.

**Comment by dnsmichi** [comment]
Yep. It just does not have a high priority if you keep using the `global-templates` and `director-global` zones which are the default for now. Should be considered once your other patches are merged, to work on a stable basis. Most likely after 2.8.

**Comment by Thomas-Gelf** [comment]
Please let me add some thoughts here. What @dgoetz describes is one of the use-cases for multiple global zones I mostly meet "out there".  Large environments are often configuring their very own global Zones for various reasons:

* not reloading all nodes for unrelated changes (mentioned by @dgoetz, works fine)
* not flushing enormous amounts of data on every reload when lots of Agents are involved (currently doesn't work as expected)
* providing sensitive information only to specific nodes (also doesn't work yet)

My conclusion is that multiple global zones are a reality right now, and will become much more important once we fixed above issues. So, people keep asking for this. That's why something similar finished in the PowerShell-based installer and is configurable in Director v1.4.0:

![director_self-service_zones](https://user-images.githubusercontent.com/553008/31487815-0140b3d6-af3c-11e7-97a8-3445c6590ed0.png)

Judging prio is not up to me, just wanted to explain why this might be important for some users.

**Comment by mcktr** [comment]
Implemented in #5767 and #6170 

Closed.
