### ISSUE TITLE
[dev.icinga.com #10733] slaves can't modify objects (ack, comment, downtime)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3719]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10733

**Created by penyilas on 2015-11-26 17:18:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-09 14:52:21 +00:00 (in Redmine)_

    Icinga Version: 2.4.1
    Backport?: Not yet backported
    Include in Changelog: 1

---

Hi,

I've a 2 master 2 satellite configuration
I'm running icinga-web2 on satellites (because they've more resources, than the masters)

On 2.3.11, it worked perfectly, but now, I can't ack a problem, schedule downtime, etc, because:

warning/ApiListener: Discarding 'config update object' message from 'slave1'

If I install an icinga-web2 into master, it's working again, but I'd like to avoid it.

Can you add some exceptions into here?
https://github.com/Icinga/icinga2/blob/master/lib/remote/apilistener-configsync.cpp#L91

Regards,
Peter Nyilas

---

**Relations**:

* relates [#10505](https://dev.icinga.com/issues/10505)
* relates [#10733](https://dev.icinga.com/issues/10733)

**Comment by xenuser** [comment]
I can confirm this bug with Icinga 2.6.1. It would be great to see if this issue could be fixed any time soon. In enterprise environments, it could be the case that e.g. Icinga clients schedule a downtime for themselves at their responsible satellite (e.g. before a reboot). In this case, we can not allow the clients to talk to the master directly, which is why it would be great to see that creating downtimes on satellites actually works again.

**Comment by dnsmichi** [comment]
That behaviour changed in 2.4 and we haven't touched it ever since. It has been discussed a while ago in #4969 although it is unclear whether we change it back, or not. For the time being, this isn't really a bug anymore but a current behaviour which might need changes. We don't have any plans or time currently to look further into it, but you're welcome to suggest possible design changes (as a matter of security) or send a PR even :)

**Comment by dombyy** [comment]
I have same issues with my nodes after upgrading from 2.4.x to 2.6.1. 

"warning/ApiListener: Discarding 'config update object' message from"

Of course accept_config is true.

**Comment by jar361** [comment]
I have the same issues with my nodes on version 2.6.2-1

**Comment by xenuser** [comment]
@dnsmichi  Thanks for the fast reply. I will contact you directly during the Icinga Camp then, I guess :) Would be great to hear some more thoughts regarding the design decisions and how a possible change could look like.

**Comment by dombyy** [comment]
I just compiled from the source, and working fine again. Previously I tried via DEB packages.

**Comment by dnsmichi** [comment]
@dombyy Uhm I doubt that compiling from source changes anything regarding the requested behaviour. What exactly did you test?

**Comment by dombyy** [comment]
I did not do test, i just upgraded from 2.4.x to 2.6.1, and nodes stopped sync the configs. Then I grabbed the source, compiled everything, and its working again, with the 'Discard config' messages.

**Comment by gunnarbeutner** [comment]
There are no plans to support this.
