### ISSUE TITLE
[dev.icinga.com #11071] Add option to specify ServiceDescription instead of ServiceName with check_service.exe

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#3891]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11071

**Created by minibbjd on 2016-02-02 19:40:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-02-04 21:47:48 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Currently you have to pass the ServiceName to check\_service.exe:
cmd&gt; check\_service.exe -s AppHostSvc
SERVICE OK RUNNING | service=4;;;1;7

It would be very handy to be able to pass the ServiceDescription aka DisplayName like this:
cmd&gt; check\_service.exe -d "Application Host Helper Service"

Some C** code to enumerate Windows services is here: http://www.go4expert.com/articles/installed-windows-services-cpp-t18601/

**Comment by dgoetz** [comment]
@Crunsher: Is this something you can have a look into? I typically prefer using the Name instead of the Displayname as it will have no whitespaces or special characters, but now I had a system with really ugly service names but nice and helpful service displaynames.

NSClient++ does also allow for use of both, so perhaps borrowing code from there is an option if it is better as the example above.

**Comment by Crunsher** [comment]
I thought I fixed that, I was sure of it even... Turns out I had the changes stashed away locally for half a year ^_^

I'll review it and push it into the master after the 2.7 release

**Comment by Crunsher** [comment]
Closed with #5435
