### ISSUE TITLE
[dev.icinga.com #11436] Add LogstashWriter for Logstash in addition to GelfWriter

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4054]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11436

**Created by twidhalm on 2016-03-22 15:49:55 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _2.7.0_
Last Update: _2016-11-09 15:11:53 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

The GELF protocol can use UDP or TCP according to the documentation.

Since some GELF receivers (like Logstash) can only receive UDP and the Icinga 2 GELF writer can only send TCP we have the situation that 2 tools talking the same protocol still can't talk to each other.

Could you add a protocol switcher to the GELF writer object?

**Changesets**

_2016-06-15 13:21:28 +00:00_ by _kgoller_ 8ad95bdfed83601492ad2e6dde263e348645829f

    Delete unused files
    
    refs #11436

_2016-06-15 13:27:26 +00:00_ by _kgoller_ ce7a23cf049153662b83d092a776b5cd0fa4f7ec

    Delete more unused files
    
    refs #11436

_2016-07-06 11:51:59 +00:00_ by _kgoller_ cd785ae577e4a81de76d3fb0fc7ca17649ee8699

    add UDP support
    
    - icinga can now use UDP to communicate with logstash;
    	switch protocol in logstash.conf
    
    refs #11436

_2016-07-06 12:07:15 +00:00_ by _kgoller_ 50e4c35bc9d4c65d3a7a70cd494e5a614c9d2b8f

    delete comment
    
    refs #11436

_2016-07-11 19:03:41 +00:00_ by _kgoller_ ea5aadf8eb0f719d5998e22740573a9936335ae0

    fix several small issues
    
    -removed some unneeded changes
    -fixed several typo errors
    -moved TcpSocket::Connect() into class Socket
    
    refs #11436

_2016-07-14 07:21:20 +00:00_ by _kgoller_ 1db4852d8eb4c0aa5928d8c536dfd16dfd324209

    Remove pointer
    
    refs #11436

---

**Relations**:

* blocks [#11436](https://dev.icinga.com/issues/11436)

**Comment by dnsmichi** [comment]
Code was not in a good shape, and at least the performance data part is still incomplete.


### Tests

Use the `icinga2x-elastic` box. Logstash 5.x requires the udp plugin to be manually installed.

```
/usr/share/logstash/bin/logstash-plugin install logstash-input-udp logstash-codec-json
systemctl restart logstash
```

Configure the input and output.

```
vim /etc/logstash/conf.d/icinga2.conf

input {
  udp {
    port => 5555
    codec => json
  }
}
output {
  elasticsearch {
    hosts => [ "localhost:9200" ]
  }
}
```

Then point Icinga 2 to it inside `features-enabled/logstash.conf`.

```
object LogstashWriter "logstash" {
  host = "192.168.33.7"
  port = 5555
  //port = 9201
  //socket_type = "udp"
}
```

Note: The logstash input port is freely assignable, there is no sane default.

### Discussion

I'm not entirely convinced if the udp input makes sense since both logstash and elasticsearch provide a HTTP API. Elastic beats are providing output methods for both interfaces, so they probably do not differ that much.

The JSON blob is entirely written to Logstash, so you'll need to use the json codec on your own if your prefer just that.

![screen shot 2017-01-24 at 18 15 29](https://cloud.githubusercontent.com/assets/382049/22258303/53dd84a0-e261-11e6-9dbb-02450e45618c.png)

**Comment by sgovaerts** [comment]
@dnsmichi Any update about this?

**Comment by dnsmichi** [comment]
Still on my TODO list.

**Comment by dnsmichi** [comment]
I'm postponing this feature until there is a general decision about an ElasticWriter feature. There's a possible sponsor for that.

**Comment by sgovaerts** [comment]
@dnsmichi Just wondering if anything's changed..

**Comment by dnsmichi** [comment]
There are plans to introduce a generic ElasticWriter, sponsored by a customer. Nothing new in this issue though.

**Comment by sgovaerts** [comment]
Ok, thank you for the quick response. Was just wondering since I couldn't find anything under ElasticWriter.

**Comment by dnsmichi** [comment]
We'll create an issue once the spec and assigned devs are clarified.

**Comment by dnsmichi** [comment]
Closing this in favor of #5538.
