### ISSUE TITLE
[dev.icinga.com #12684] windows service not starting on SBS2011

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4656]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12684

**Created by kpjbvc on 2016-09-09 13:04:04 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-09 13:04:04 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Platform: Windows Small Business Server 2011, Icinga2 2.5.4 x86\_64. After installation the windows Icinga2 service crashes at startup. Debugging on command line with 'icinga2.exe daemon -x debug' gives following logging:

\[2016-09-09 14:58:37 Romance Daylight Time\] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
\[2016-09-09 14:58:37 Romance Daylight Time\] information/cli: Icinga application loader (version: v2.5.4)
\[2016-09-09 14:58:37 Romance Daylight Time\] information/cli: Loading configuration file(s).
Could not create directory 'C:\\jenkins\\workspace\\icinga2-windows-package\\arch\\x86\_64\\label\\windows\\inst\\var\\log\\icinga2\\crash': Error 2, No such file or directory
\[2016-09-09 14:58:37 Romance Daylight Time\] critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in 'C:/jenkins/workspace/icinga2-windows-package/arch/x86\_64/label/windows/inst/var/log/icinga2/crash/report.1473425917.856000'
\[2016-09-09 14:58:38 Romance Daylight Time\] notice/ThreadPool: Pool [\#1:](https://dev.icinga.com/issues/1) Pendingtasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0%

Version 2.4.4 works. I don't think the windows version is causing the issue, rather some problem with reading the Windows Installer info from the registry.

**Comment by dnsmichi** [comment]
#4064 attempts to solve this. @TheFlyingCorpse any ideas here?

**Comment by TheFlyingCorpse** [comment]
I installed a SBS 2011 server, unable to replicate this behavior.
- Installed Icinga2 2.4.4
- Verified its operational. + tested the reported debug command.
- Installed Icinga2 2.5.4 (x86_64)
- Verified its operational + tested the reported debug command.

If you still experience the problem, take a backup of any extra scripts/plugins you have installed in the Icinga2 folder(s), uninstall Icinga2 and install one of the newer ones.

I do not understand how the original reporter could get those paths from the output, that looks like a borked setup itself as some of the paths are hardcoded since 2.4.5, specifically the %PROGRAMDATA%\Icinga2 ones where Icinga2 has its configuration, certificates, state, crash and logfiles.

**Comment by dnsmichi** [comment]
Thanks for the fast response. So we can close it :)
