### ISSUE TITLE
[dev.icinga.com #12939] Acknowledgement date changes after reload/restart icinga2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4739]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12939

**Created by maelig on 2016-10-18 12:35:19 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-18 12:35:19 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

My setup:
- checker zone with 2 nodes
- master zone with 2 node as parent zone
- icingaweb2 et icinga2 classic

I noticed on icingaweb2 or icinga2 classic than the date of creation of some acknowledged is modified after reload of icinga2. The date is set to the last reload.
Example :
Service 'Swap' of server inventory01g : acknowledged on Sep 30 (before reload)
Service 'Swap' of server inventory01g : acknowledged at 09:06 (after reload)
Service 'Swap' of server inventory01g : acknowledged at 13:06 (last reload)

**Comment by dnsmichi** [comment]
Sorry, that issue slipped through my scrolling over tickets review. An acknowledgement points to a comment - can you verify that the underlaying comment object has the "entry_time" set correctly (should be in /var/lib/icinga2/api/packages/_api/...) and the REST API does not return "now" for it? There was a bug in 2.5.x which has been fixed in the meantime.

**Comment by dnsmichi** [comment]
Supposed it is fixed.
