### ISSUE TITLE
[dev.icinga.com #13377] Acknowledgements marked with Persistent Comment are not honored

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2#4818]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13377

**Created by TheFlyingCorpse on 2016-12-01 11:12:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-16 22:01:36 +00:00 (in Redmine)_

    Icinga Version: 2.5.4
    Backport?: Not yet backported
    Include in Changelog: 1

---

Acknowledgements marked in IcingaWeb2 as a persistent comment are not stored once the service or host recovers.

I have verified the bit is set correctly in the external command submitted to Icinga2.

The code does not seem to use the flag set.

AcknowledgeHostProblem
https://github.com/Icinga/icinga2/blob/09658f6d0e92db179301197d85067bf2fdc45a89/lib/icinga/externalcommandprocessor.cpp#L679

AcknowledgeSvcProblem
https://github.com/Icinga/icinga2/blob/09658f6d0e92db179301197d85067bf2fdc45a89/lib/icinga/externalcommandprocessor.cpp#L620

**Attachments**

* [0001-Fix-the-behaviour-of-persistent-comments-from-acknow.patch](https://dev.icinga.com/attachments/download/3887/0001-Fix-the-behaviour-of-persistent-comments-from-acknow.patch) TheFlyingCorpse - _2016-12-07 21:57:52 +00:00_
* [0003-Honor-persistent-comment-from-acks-with-expiry.patch](https://dev.icinga.com/attachments/download/3889/0003-Honor-persistent-comment-from-acks-with-expiry.patch) TheFlyingCorpse - _2016-12-07 23:23:24 +00:00_ - _Honor persistent also from acks with expiry_
* [0002-Do-not-expire-comments-set-as-persistent-from-acknow.patch](https://dev.icinga.com/attachments/download/3891/0002-Do-not-expire-comments-set-as-persistent-from-acknow.patch) TheFlyingCorpse - _2016-12-07 23:23:24 +00:00_ - _IDO patch_

---

**Relations**:

* relates [#13377](https://dev.icinga.com/issues/13377)

**Comment by dnsmichi** [comment]
Hm, IIRC `persistent` means that such a comment will survive a core restart. That is a fairly strange setting in 1.x since you reload the core quite often. That is what you get when you call "ADD_SVC_COMMENT" as an external command. We decided to skip that and make comments persistent over restarts all the time.

In case you're using persistent with an Acknowledgement type and comment, it gets a different meaning. Then `persistent` means to keep the comment even if the acknowledgement is removed (thus a recovery).

Your patch attempts to fix this, and by using RemoveCommentsByType(CommentAcknowledgement) this certainly already works, although missing the persistent attribute check.

The thing which bugs me the most - how to handle the new `persistent` attribute for a) all other comments b) upgraded systems.

For a) - that settings remains useless, for b) if not explicitly set in the config, it must return `true` inside the comment.ti file to keep the same behaviour as known from older versions.

**Comment by dnsmichi** [comment]
Well, and since `persistent` is a boolean value type then, it should use `bool` instead of `int` everywhere.

**Comment by TheFlyingCorpse** [comment]
On using int instead of bool: I used int because that was what came in over the external command processor and already used with the apiaction I looked at for reference, I'll update in a few days.

Am I allowed to use commenttype to decide the outcome of persistent? That could decide when to honor the persistent or not, if its any other type than Ack, set to false. Thats the same way for upgraded systems, its false by default since you dont know what state it was set with (which is what this PR tries to fix)
