### ISSUE TITLE
CentOS: deploy service file for firewalld

### ISSUE THREAD

**Issue by janvonde** [Icinga/icinga2#4931]
CentOS comes with a default firewall enabled based on firewalld. It can be extended using service files. I'd like to suggest to distribute an icinga service file for firewalld with the CentOS packages. The file could look as follows:

    <?xml version="1.0" encoding="utf-8"?>
    <service>
      <short>icinga</short>
        <description>Icinga is a resilient, open source monitoring and metric solution based 
         on a new object-based, rule-driven configuration. If you plan to use it's agent and 
         want to listen for connections, enable this option. You need the icinga2 package 
         installed for this option to be useful. </description>
        <port protocol="tcp" port="5665"/>
      </service>

**Comment by dgoetz** [comment]
We already tried to integrate it, but had to drop this feature again because of dependencies required to do it correctly broke docker installations.

See: https://github.com/Icinga/icinga2/issues/3708 and https://github.com/Icinga/icinga2/issues/4526

But we will try to get the port assigned and then get this directly into firewalld upstream in the future.
