### ISSUE TITLE
Dependencies may reschedule passive checks, triggering freshness checks

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#5022]
Setup: Two passive services A and B, where A depends on B with freshness checks using check_dummy and check/retry_interval.

If service A changes its state, the code at  https://github.com/Icinga/icinga2/blob/55e7de38024096ac70ac936cb7b65d9dfa79ad20/lib/icinga/checkable-check.cpp#L247 reschedules service B for an instant recheck. This brings it to a critical/unknown state indicating that no passive results were submitted for B, even though the active check for B is only intended as a freshness check for the passive check results and passive data for B is submitted in time.

**Comment by vanscheijen** [comment]
I believe this code could benefit from some exclusions. First to ignore rescheduling parents if they are passive. And secondly to not reschedule if the next check is within the retry interval, this prevents reschedule storms that occur when there are may services depending on a single one, e.g. one NRPE parent. This can cause a NRPE notification within a single second because the max retry is reached too quickly.

My code suggestion, however please validate:

```
    if (parent->GetEnablePassiveChecks())
        continue;

    double now = Utility::GetTime()
    if (parent->GetNextCheck() >= now + parent->GetRetryInterval())
        parent->SetNextCheck(now);
```

**Comment by julianbrost** [comment]
The "if they are passive" thing is a bit problematic since `enable_passive_checks` defaults to true. So this would disable rescheduling for everything unless passive checks are explicitly disabled.

**Comment by vanscheijen** [comment]
Thanks julianbrost, I forgot about that. It would be better to check if it is active, because you should never reschedule a non-active check, thus:

```
    if (!parent->GetEnableActiveChecks())
        continue;
```

**Comment by jonans** [comment]
Any reason this is not tagged a bug ? Its very useful feature but can't be used in passive rich environments because of this.

**Comment by Crunsher** [comment]
Relevant PR: #5375
