### ISSUE TITLE
IDO isn't updated on check_period removal

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#5037]
https://github.com/Icinga/icingaweb2/issues/2697

**Comment by Al2Klimov** [comment]
For the record: the config object hash **changes** so this is not the cause.

**Comment by TheFlyingCorpse** [comment]
Tested:
- New timeperiod used as expected.
- Changed timeperiod used as expected.
- From defined to no timeperiod, bug reproduced.

Looking at the "Checkable" for check_period it tries to return a raw result when it is defined.
I guess since it is not configured it will never try to return the data from this (GetCheckPeriod()), when what we want back for IDO is a reference to either 0 or NULL (the schema is default 0).

**Comment by dnsmichi** [comment]
Parent ticket for solving these problems is #6012.
