### ISSUE TITLE
icinga2 2.6.0+ centos 6 x86_64 package launching processes incorrectly

### ISSUE THREAD

**Issue by mbassett** [Icinga/icinga2#5048]
On icinga 2.6.0  when it launches it looks like:

icinga   18045     1  0 Mar01 ?        00:02:05 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/error.log --reload-internal 16595
icinga   18061 18045  0 Mar01 ?        00:00:14 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/error.log --reload-internal 16595

This looks good, as you can see the second process is owned by the first process, and the first process is off root 1

However, in 2.6.2 on cent 6 x86_64 we now get:
icinga    9440     1  0 00:43 pts/0    00:00:00 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -c /etc/icinga2/icinga2.conf -d -e /var/log/icinga2/error.log
icinga    9445     1  1 00:43 ?        00:00:00 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -c /etc/icinga2/icinga2.conf -d -e /var/log/icinga2/error.log

both processes are launched off root process, and the first process does nothing but sleep and sleep and sleep.

**Comment by mbassett** [comment]
this may effect other platforms but all my nodes are x86_64

**Comment by AlexanderS** [comment]
Probably related with #5038.

**Comment by kobmaki** [comment]
I compile it on different plattforms (x86_64, armv7l, aarch64) on debian.  I saw this behavior since a few month too. It might be introduced around 2.6.0 as an old version v2.5.4-112-gefbdce8 didnt't have this behavior. My actual "oldest" icinga2 version with this behavior is v2.6.1-40-g2c510d2. 

On a debian system with release from the icinga repo ( v2.6.1-34-g14fc977 and v2.6.1-67-gbb2ee7f ) didn't show this behavior if you start icinga2 via systemd. But if you start the process by hand like:

`icinga2 --no-stack-rlimit daemon -c /etc/icinga2/icinga2.conf -d -e /var/log/icinga2/error.log`

you see the similar behavior.

The written PID file contains the correct working process.

  `cat $(icinga2 variable get PidPath)`

On Linux systems the command:

`pgrep -P 1 -u $(icinga2 variable get RunAsUser) -x icinga2`

shows two pids. 

The oldest process couldn't be kill by signal TERM. You have to kill it with the signal -9.
So, you can kill the oldest one by:

`kill -9 $(pgrep -P 1 -u $(icinga2 variable get RunAsUser) -x icinga2 -o)`

Take care to run this command only once, and not twice times ;-)
The correct icinga2 process is still running.

**Comment by mbassett** [comment]
I can confirm in centos 6.8  64bit   

icinga2-common-2.5.4-1.el6.x86_64

icinga   14822     1  0 00:34 ?        00:00:00 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -c /etc/icinga2/icinga2.conf -d -e /var/log/icinga2/error.log

icinga2.x86_64 0:2.6.0-1.el6  

icinga   15575     1  0 00:38 pts/0    00:00:00 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -c /etc/icinga2/icinga2.conf -d -e /var/log/icinga2/error.log
icinga   15578     1  1 00:38 ?        00:00:00 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -c /etc/icinga2/icinga2.conf -d -e /var/log/icinga2/error.log

**Comment by dnsmichi** [comment]
Could be related: #4924
