### ISSUE TITLE
Store event log in database and use it instead of compat log for livestatus log queries

### ISSUE THREAD

**Issue by mickenordin** [Icinga/icinga2#5053]
Today it seems the livestatus implementation relies on the compat logs for the "GET log" query. This is extremly slow even if you have a medium sized environment.

I would propose a dblogger feature that would store event history in a database such as mysql which would allow indexing and partitioning of the data making queries faster and data more easily managed. It would also mean that data is not duplicated a cross a cluster since only one of the servers write to the database at a time.

**Comment by dnsmichi** [comment]
I'd suggest to use a database exactly for that. The livestatus log table has been added for compatibility reasons, but turns out that (ab)using livestatus as a database isn't really a good idea. A monitoring core shouldn't act as historical backend.

Even Thruk fetches the log data and caches that in a local database for the reporting jobs. And you'll certainly already have the IDO feature enabled for Icinga Web 2. So I'd suggest to query that backend, or the Icinga Web 2 REST API for retrieving such data.

We won't fiddle with the Livestatus API and change the compatlog to something else. That's a dead end, and not our primary development focus, sorry about that.
