### ISSUE TITLE
EventHandler to be executed at the endpoint

### ISSUE THREAD

**Issue by emanuel-b-q** [Icinga/icinga2#5090]
Hello developers,
I am trying to execute a eventhandler at a specific node.
Currently this seems to be impossible, right?

**Comment by dnsmichi** [comment]
If you're using command_endpoint for that node (host/service check which has the event command configured), event handlers will be executed there similar to check commands.

**Comment by dgoetz** [comment]
Thanks for clarifying this.

It is already in the docs, but only as a small note in 3.8.3 and then the example uses ssh.
`If you are using a client as command endpoint the event command will be executed on the client itself (similar to the check command).`

Do you have any ideas who we can make users more aware of it? I am thinking about adding it to the object and perhaps another example locally executed on the command endpoint.

**Comment by dnsmichi** [comment]
Imho event handlers are somehow quirky and require further programming knowledge. I'm not happy with the current documentation and the proposed scripts (neither works on Windows e.g.), nor the way how such scripts require arguments. There's also an issue somewhere which asks for specifying an event command endpoint in addition to the current command_endpoint attribute.

Basically, that feature requires some love with more practical examples and rewritten documentation. Anything else is probably solved by using API event streams and farther integrations (rather than managing that on a per host/service object level).

**Comment by Thomas-Gelf** [comment]
Ist drin - nochmal geändert und komplett ungetestet, also bitte schreien 
wenn's nicht läuft :p Mahlzeit!

Am 29.03.2017 um 11:03 schrieb Dirk Götz:
