### ISSUE TITLE
GraphiteWriter can slow down Icinga's check result processing

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga2#5132]
In larger installations the GraphiteWriter might actually slow down the processing of CheckResult messages.

My assumption is that the messages are stuck inside `l_JsonRpcConnectionWorkQueues` due to the synchronosity of GraphiteWriters flushes.

Problems:
* All writes in GraphiteWriter are done synchronous on calls to `CheckResultHandler`
* Object is locked by `SendMetric`

You would need a really fast Graphite to allow that to work.

We will test out https://github.com/graphite-ng/carbon-relay-ng as a local buffer.

@dnsmichi suggested that we should think about a Queue and Bulk writes

**Comment by lazyfrosch** [comment]
I would also prefer to have stats for:
* Amount of checkresults processed, with and without perfdata
* Metrics pushed to Graphite (split by meta and perfdata)
* Details on the current Queue size

**Comment by dnsmichi** [comment]
@lippserd please note this one for further analysis.

**Comment by jediblair** [comment]
Not sure if this issue is related, but I've got a setup where I'm using Logstash to read the GraphiteWriter stats, and output to Elasticsearch. If the Elasticsearch end has an issue (eg, disk full, or some other error), then Icinga2 seems to lock up and potentially memory leak leading to OOM killer. 
This also results in the API not functioning correctly, check results not being processed, and IcingaWeb2 shows Icinga2 being down. 

This is using Icinga2 2.6.3, Elasticsearch/Logstash 5.3.1

**Comment by lazyfrosch** [comment]
We probably should introduce the same queue as in #5232

**Comment by dnsmichi** [comment]
You can use carbon-cache-ng or carbon-relay as workaround for now.

The queue thing is only partially the same as in the InfluxDB code, since we keep an open tcp stream.

**Comment by dnsmichi** [comment]
I'll fix that in PR #5287 :)
