### ISSUE TITLE
Change request: host downtime should result also to the services 

### ISSUE THREAD

**Issue by C-Hoelscher** [Icinga/icinga2#5176]
Is it possible that set a host downtime over the Webinterface also have result to his services?
What I meen is: set a downtime for a host should also set downtime for assigned services.

Currently I can set a downtime for an host ( for maintenance or installing updates) and set the check box "all services", but when I'm ready and delete the downtime for the host, the services are still in downtime, and I must remove the downtime for every services separat.

Same issue for downtimes from host with dependent hosts: deleting downtime for main host does not remove the downtime for the dependent hosts. 

I currently use Icinga2 r2.6.2-1

**Comment by dnsmichi** [comment]
This is an Icinga Web 2 feature request, please open it over there: https://github.com/icinga/icingaweb2/issues

**Comment by C-Hoelscher** [comment]
Hello, you have closed this ticket with the note "This is an Icinga Web 2 feature reques"
but it is not an Icinga2Web request, it belongs direct to icinga2.
It does not matter where the downtimes come from, WebGUI (icingaweb2 or classiui) or icinga.cmd (SCHEDULE_HOST_DOWNTIME). 
Set an Host downtime has no effect to his Services, and set an Host Downtime with his Services (SCHEDULE_HOST_SVC_DOWNTIME) and you delete the Host downtime (DEL_HOST_DOWNTIME) his Services are still in Downtime.
And that makes no sense for me.

**Comment by dnsmichi** [comment]
I'm not sure I can follow. There is required app functionality here: You'll need to know about a host object and related services, and then fire away. Be it creating downtimes, or deleting them all.

There's currently no functionality in Icinga Web 2 to delete a host downtime and all of its service downtimes as far as I can see. Programmatically this would involve to a) delete the host downtime b) iterate over all host services and delete the downtime.

b) can be solved by using the API command transport and just using the filter `host.name == HOST` instead of firing multiple downtime service delete commands.

So the functionality for both types already is there inside the REST API, you just need to use them.

That is why I am pointing to Icinga Web 2, since you probably would want to have that feature available via web interface.

One thing to note here: We won't add features to the external command pipe, nor Icinga 1.x related legacy interfaces such as the Classic UI.
