### ISSUE TITLE
Local checks with same servicename do not trigger an error

### ISSUE THREAD

**Issue by dupondje** [Icinga/icinga2#5385]
## Current Behavior
In a setup with a master node an config sync to its 'agents', we do all the config work on the master node.
This also includes for example alert thresholds on disks (5% free space => critical).

Now by default Icinga2 ships a "disk" check in the conf.d folder, which contains other (linux) or no (windows) tresholds.
What we notice is that not the thresholds from the master node (via config sync) are used, but the thresholds from the client (in the conf.d config) are used!

This is a big risk if you miss to comment the conf.d include in icinga2.conf, then you might risk to not get alerted when a disk is full on a Windows machine. Or you get wrong alerts on Linux.

## Expected Behavior
I would expect at least that Icinga2 gives an error on startup/config sync, that there is a duplicate service name. This is not the case now, making the issue invisible.

It would also be nice if the 'icinga' check_command was able to give an alert of this. This way it would be visible that something is wrong.

**Comment by TheFlyingCorpse** [comment]
The Icinga check command does alert you, it turns to warning in my environment since the last reload failed in such scenarios.

**Comment by dnsmichi** [comment]
The described behaviour only occurs if the following scenario is in place:

- master with hostA which fires the check via command_endpoint
- client hostA which has local configuration for hostA in conf.d **and** the checker feature enabled

client hostA executes checks on its own. It has a) a local host object `hostA` b) the checker feature enabled.

These checks are synced via the cluster protocol to the top where the master processes them. Sometimes these check results are received from local client check results, sometimes they are executed via command_endpoint.

There's no solution for that, other than to a) don't enable conf.d if you don't need it i.e. for command_endpoint checks b) disable the checker feature on command_endpoint clients. At least a) is explicitly noted inside the docs due to this behaviour.

One "fix" could be to make the "conf.d" configuration files optional (#4865) which itself depends on the deprecation and removal of the "bottom up" client node (#4799).

Either way, I suggest to create "clean" configuration and only enable objects you really depend on for your monitoring.

**Comment by dupondje** [comment]
Thanks for information @dnsmichi 

The risk here is that you need to manually disable conf.d and/or the checker. Which are enabled by default. If on a friday somebody forgets this step, nothing makes you aware of it (no error, no warnings, checks just works ... etc). This is the biggest issue.
I agree we should just comment the 'conf.d' in the config, but I would like to make it less error-prone.

I think there are several options:
1) Disable conf.d by default
2) Disable checker by default
3) Give warnings/errors in the icinga check when this case happens (same check via command_endpoint and client conf.d)
4) Optional argument on the icinga2 check which checks if 'checker' is disabled for example?

**Comment by dnsmichi** [comment]
It is hard to determine additional objects upon command_endpoint execution and put a warning somewhere. You won't detect such problems during config validation either.

I strongly suggest to **manage** your monitoring deployments, i.e. roll out clients with Puppet, Ansible, etc. and ensure that a) conf.d is disabled b) checker feature is not enabled.

**Comment by dnsmichi** [comment]
I've added that to the troubleshooting docs recently with #5487 - the rest will be solved by the referenced issues.
