### ISSUE TITLE
Startup errors are not logged by Icinga 2

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icinga2#5399]
In case the configuration is not valid or the Icinga 2 state file is corrupt, there is no way to determine the current Icinga 2 problems within the logfiles, making it harder for debugging.

Especially when the state file is corrupt the only way is to start Icinga 2 in foreground to become aware of the problem.

## Expected Behavior

Load the LogHandler at the very beginning and log all events into the Icinga2.log or debug.log

## Current Behavior

Startup problems are neither logged within the Icinga2.log or the debug.log

## Possible Solution

Load LogHandler at the very beginning before anything else

## Steps to Reproduce (for bugs)

1. Corrupt the state file / the Icinga 2 config
2. Restart Icinga 2
3. Take a look into icinga2.log / debug.log - no events occur there

## Context

Took quite some time to figure out why the Icinga 2 Agent on Windows was not starting. This problem does occure on Linux systems as well.

## Your Environment

* Version used (`icinga2 --version`): All
* Operating System and version: Windows and Linux

**Comment by Crunsher** [comment]
Startup problems should be logged by syslog. We can't write out these problems to the log that early in the startup as the logger does not exist yet that point.

A possible improvement would be to have `icinga2 daemon -C` check the statefiles sanity

**Comment by dnsmichi** [comment]
It is a known issue, but no patches or ideas how to properly solve it yet. Patches welcome.

**Comment by sourcejedi** [comment]
> This problem does occure on Linux systems as well.

I don't know how this works under Windows, but I'm surprised at the Linux part.

AFAIK, looking at the current version of icinga, you should either get a message telling you to look in the systemd journal, or in a specific startup log file.

Note, in the systemd case, you need use a privileged user to look at the journal.  Otherwise, you might see only log messages from your own user, and not from system services.

There might be cases where that message is a lie, and the real error is in a separate `icinga.err` log instead.  But I wouldn't have thought that was the case if the state is corrupt.  E.g. I get success messages in the systemd journal:

```
Jun 06 17:11:16 stretch2 icinga2[21164]: [2018-06-06 17:11:16 +0100] information/ConfigObject: Restoring program state from file '/usr/var/lib/icinga2/icinga2.state'
Jun 06 17:11:16 stretch2 icinga2[21164]: [2018-06-06 17:11:16 +0100] information/ConfigObject: Restored 262 objects. Loaded 0 new objects without state.
```

and this seems to be before the point in the code, where stderr would be redirected to `icinga2.err`.

**Comment by sourcejedi** [comment]
Ah, I guess Debian doesn't use the upstream initscript. It looks as if it uses the same startup log file, but only for configuration errors... I'd really think anything else would get printed to the console.  Maybe I'm missing something though.

**Comment by Al2Klimov** [comment]
Doesn't ${LOG_DIR}/error.log fit your need?

**Comment by lippserd** [comment]
If the configuration is invalid or the state file corrupt or any other problem prevents Icinga 2 from starting, nothing is written to the error.log.

**Comment by Al2Klimov** [comment]
Note: Config and state loading errors on Linux are covered by either the icinga check or #7874.

**Comment by Al2Klimov** [comment]
@LordHepipud Any idea what's the equivalent of #7874 of Windows?

**Comment by LordHepipud** [comment]
In general my first approach is looking inside the Windows Eventlog on why a service wouldn't start. So the best approach in my eyes would be to send such errors directly to the Application EventLog on Windows and include as much details as possible to help me troubleshooting.

**Comment by julianbrost** [comment]
Probably yes, that's the reason for the "additionally" in my comment. Try to log to all available channels (that somewhat make sense) until we loaded the logging configuration.

**Comment by Al2Klimov** [comment]
Tbh I'm fine w/ #7874 + #8009. Less (info) is more.

**Comment by julianbrost** [comment]
I don't agree with that. Why would you want to write new log messages to the Windows Event Log where you intentionally omit information that would be available (https://github.com/Icinga/icinga2/pull/8009/files#diff-7e11977c3755eeab8a9f2909db775977bc49d02d469a0d65022f8f220d7e9187R324) instead of just writing the regular log message? These short messages make sense for the sd_notify API that exists precisely for such messages (**in addition** to the regular log).

With this, you'd get a rough idea where something went wrong, but you don't get any information on why. And the answer to "where can I find additional information?" would be "uhh, yeah, we threw that away, sorry and good luck."

**Comment by Al2Klimov** [comment]
So basically your solution of this problem is: until _activated all items_ log everything to systemd/event log, too?

**Comment by julianbrost** [comment]
Yes, so until we know where to log to from the configuration, we log to syslog or Windows Event Log. This should also give us a proper logger for the Windows Event Log that can then be configured as usual.
