### ISSUE TITLE
graceful restarts

### ISSUE THREAD

**Issue by darmagan** [Icinga/icinga2#5422]
A customer is asking about a feature in which the Icinga2 main process doesn't kill the sub check processes immediately if restarted.
Graceful would be to wait for the check_interval to end before killing a process. The problem is that if one node dies, the time between the second node to take over and re-schedule the checks, the dying node shows the hosts down.

Regards

**Comment by dnsmichi** [comment]
You cannot really do that, since the application doesn't know if the running process would last 1 millisecond or 20 seconds to finally complete. If the reload command runs that long, you'll likely a timeout kill from Systemd anyways.

The underlying problem is that application restart/reload kills a process during shutdown which generates an `UNKNOWN` check result (for hosts, 3 is handled as DOWN). That's a change request with #4364 and requires a time estimate and granted resources.
