### ISSUE TITLE
SSL errors with leading zeros in certificate serials (created < v2.4) with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#5511]
Certificate serials may not start with leading 0s since openssl 1.1.0, they should(tm) not have any in 2.7.0 but we should check just to make sure.

Further reading: http://openssl.6102.n7.nabble.com/openssl-org-4301-BUG-OpenSSL-1-1-0-pre2-fails-to-parse-x509-certificate-in-DER-format-td63467.html

**Comment by widhalmt** [comment]
@Crunsher Is this just to make sure or did you see Icinga 2 nodes having problems to start with such a serial number? I do have one Testhost which doesn't start and the error messages indicate it might have something to do with the certificates serial but I'm still searching so I didn't open a new issue.

I'm just curious if you have the same problems or if this is just a precaution.

**Comment by dnsmichi** [comment]
Precaution based on the ticket we've discussed yesterday. It is not clear if this really is a bug or not.

**Comment by dnsmichi** [comment]
https://monitoring-portal.org/index.php?thread/41664-ca-crt-verification-error-with-openssl-1-1-0-illegal-zero-content-in-field-seria/

We should verify that 2.7.x does not create invalid ca certificates. @widhalmt please share your findings from your tests once you have them.

**Comment by dnsmichi** [comment]
# How do I check that I am affected


Copy ca.crt, client.crt, client.key to that temporary container. Extract them on your box in base64 encoded strings which helps with copy paste. 

```
openssl x509 -text -in ca.crt
openssl x509 -text -in client.crt
```

Verify the certificates on a node where openssl 1.1.0 is installed (Debian Stretch for example).

```
docker run -ti debian:stretch bash
apt-get update
apt-get -y install openssl vim
```

Details: https://www.icinga.com/docs/icinga2/latest/doc/15-troubleshooting/#cluster-troubleshooting-ssl-certificate-verification

```
openssl verify -verbose -CAfile ca.crt client.crt

openssl x509 -text -in ca.crt
openssl x509 -text -in client.crt
```

### Versions involved

This likely affects the CA and client certificates created in ~2015. 

Possibly related issues: #3292, #3194, #3369 

I've tried with new certificates with 2.2.0, 2.3.0, 2.3.8 but couldn't reproduce the issue.

I think this has something to do with the OpenSSL version too (i.e. 0.9.8 or 1.0.1 or 1.0.2). Homebrew gets me `OpenSSL 0.9.8zh 14 Jan 2016` which generates working certificates on Debian Stretch (even if the version is incorrect with 1 instead of 3, and the serial is 1).

# Possible Solution

First off, check whether your CA is affected too. Create a new public CA certificate first, then re-generate the client certificates and deploy them at once.

## Re-create public CA certificate from existing key pair

This is similar how you re-generate an expired certificate. 

1.) Generate a CSR from an existing key pair (public and private key)
2.) Sign the CSR with the CA's private key

The first step needs to be done with openssl cli commands, the second step requires the icinga2 cli commands. This is mainly the reason to 

- specify the version to 3
- set a proper serial number
- enable X509v3 extensions

```
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
```

```
cd /var/lib/icinga2/ca

openssl x509 -x509toreq -in ca.crt -signkey ca.key -out regenerated-ca.csr

icinga2 pki sign-csr --csr regenerated-ca.csr --cert regenerated-ca.crt

mv ca.crt ca.crt.borked
mv regenerated-ca.crt ca.crt
```

Copy the public CA certificate `ca.crt` to **all your nodes** in `/etc/icinga2/pki/`.


### Re-create client certificates

This works in a similar fashion like the CA key pair. Create a CSR from the existing client key pair and sign it again with the private CA key on your master.

**Note**: This requires you to copy the client's public and private key to your Icinga 2 master where the private CA key is located. 

```
openssl x509 -x509toreq -in client.crt -signkey client.key -out client.csr

openssl req -text -in client.csr

icinga2 pki sign-csr --csr client.csr --cert client.crt
```

Then roll out the updated certificates to your clients. A different method is to re-run the CSR-Autosigning wizard (move away etc/icinga2/pki and re-run the wizard).

**Comment by dnsmichi** [comment]
@widhalmt it seems this can only be reproduced reliably with Debian from 2015 (Jessie I guess), OpenSSL 1.0.1f and Icinga 2 v2.3.0 on the master for generating the CA and client certificates. Please take that into account for your research.

https://monitoring-portal.org/index.php?thread/41664-ca-crt-verification-error-with-openssl-1-1-0-illegal-zero-content-in-field-seria/&postID=254852#post254852

**Comment by dnsmichi** [comment]
Updated the CA regeneration, this contained faulty signing. We need to ensure that the v3 extension sets the critical constraint to `CA:TRUE` when signing the CA certificate.

See https://github.com/Icinga/icinga2/issues/5511#issuecomment-324384804

**Comment by dnsmichi** [comment]
I couldn't reproduce the issue in a Debian Jessie container with 2.3.8, 2.3.0 and OpenSSL 1.0.1f (copying the certificates to a Debian Stretch container and validating them - works like normal).

**Comment by dnsmichi** [comment]
Note: Existing Icinga 2 setups will generate proper certificates valid with 1.1.0. This issue is solely for keeping track of affected users and possible workarounds.

**Comment by dnsmichi** [comment]
Re-iterating the error message from what we do during ApiListener::OnConfigLoaded inside MakeSSLContext(), this only affects the ca_path and in turn the ca.crt file distributed to all clients. IT does not seem to be necessary to look into new client certificates at all.

Please add your feedback on this.

**Comment by edpstiffel** [comment]
FYI
Ran into this problem while deploying icinga2-client to the first Debian Stretch machine.
Our ca.crt was from 2014/12/04.
Followed DNSMichis instructions to recreate the ca.crt based on the same key. Worked like a charm. With the new ca.crt, the icinga-client on the Stretch-machine came up.
Other clients didn't have a problem with the new cert, I didn't have to replace the ca.crt on these machines neither did I have to create new client certs.
One addition: After recreating the ca.crt, you HAVE TO copy the new ca.crt on your icinga-server  from /var/lib/icinga2/ca to /etc/icinga2/pki, otherwise you get Client TLS handshake failed errors with your new client.
Thanks for clarifying the issue and the clear instructions.

**Comment by dnsmichi** [comment]
Updated my comment. The up-to-date analysis and fix procedure is documented here: https://www.icinga.com/2017/08/30/advisory-for-ssl-problems-with-leading-zeros-on-openssl-1-1-0/

**Comment by widhalmt** [comment]
If this is only reproducible with Debian it can't be the problem I hit. This was a Windows node connected to SLES.

**Comment by dnsmichi** [comment]
Whereas the Windows package uses OpenSSL 1.1.0 which breaks on the ca.crt file during startup.

**Comment by dnsmichi** [comment]
Please follow the linked advisory and ensure to update the ca.crt on all clients (all of them, sooner or later they will receive a dist-upgrade and OpenSSL 1.1.0).

This one is informational only, therefore assigning for 2.8 to reflect it in the Changelog.
