### ISSUE TITLE
Check if 'icinga2 --version' returns the correct Windows version when run on Windows 10

### ISSUE THREAD

**Issue by gunnarbeutner** [Icinga/icinga2#5517]
Apparently --version returns "Windows 8" when run on Windows 10. Or at least it used to.

**Comment by mcktr** [comment]
I did a deep dive into the problem and found out some things. 

Simply add an additional if case to the `ReleaseHelper(String *platformName, String *platformVersion)`  function won't solve the problem. The function will not output any version above 8. 

The problem is that the manifest file is missing.

> Applications not manifested for Windows 8.1 or Windows 10 return false, even if the current operating system version is Windows 8.1 or Windows 10. To manifest your applications for Windows 8.1 or Windows 10, see Targeting your application for Windows.

https://msdn.microsoft.com/de-de/library/windows/desktop/dn424962(v=vs.85).aspx

In e7c2463f2fb712f5aa4f3568af4789d2edaf9fee I added an manifest file and added an if case for Windows 10. So far this works on my Windows 10 build system. I guess there needs to be some changes to the CMakeLists.txt to include the manifest file when creating the build environment for Visual Studio.

**Comment by mcktr** [comment]
In my last commits (f197b0281bd13f6ca49f689f0cc7b08f64650163 & b3efd9b34684d2509416581231cc90eb652a64ed) on [mcktr/fix/windows-version](https://github.com/mcktr/icinga2/commits/mcktr/fix/windows-version) I added the `icinga.manifest` file to the CMakeList.txt so I was able to build icinga2 with included manifest file from the git repository. I also reduced the content of the manifest file to an minimum. 

I read about some compatibility issues when using the function `IsWindows10OrGreater()` and building on a non Windows 10 system. This case I couldn't test yet cause I currently don't have access to an build environment which is not a Windows 10 system. But I also don't know how problematic this could be.

**Comment by mcktr** [comment]
Found out that the function `IsWindows10OrGreater()` depends on the Windows 10 SDK. If you using Visual Studio 2017 the Windows 10 SDK should shipped through the installation. When using Visual Studio 2015 the Windows 8.1 SDK is shipped during the installation, so you need to install the Windows 10 SDK afterwards and have to set the target version to 10 (for lib/base). 

But when changing the target version to 10 (within Visual Studio 2015) there is a link issue. Visual Studio can not found the `rc.exe`. I found this [Stack Overflow article](https://stackoverflow.com/questions/43847542/rc-exe-no-longer-found-in-vs-2015-command-prompt), but I haven't tested this yet. Maybe this is even an isolated problem on my build environment. 

I will do more tests and then I will share my experiences here.

**Comment by dnsmichi** [comment]
I'd say we leave this for the time being. Upgrading to VS 2017 isn't an option yet. There's also a linker problem with crlchecktask.cpp right now.

**Comment by dnsmichi** [comment]
I've played around with it, and that version "API" isn't really satisfying nor the way how 10 is detected. If one could just use the version extract function, all would be good. Unfortunately that one is deprecated. I'll close here.
