### ISSUE TITLE
Add `endpoint` variable to `cluster` check

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#5531]
Running the `cluster` CheckCommand on Nodes with lots of connected endpoints gives a very long output and most of the time Criticals when someone just shuts down one node.

Could you add an option to restrict the checks to one or just some endpoints? So one could use the check without arguments just for creating perfdata and with arguments to check e.g. if a satellite is connected to its peer.

**Comment by dnsmichi** [comment]
Isn't that more reasonable to enable this for zones, rather than endpoints where you do not necessarily know about their relationship when defined as parameter?

**Comment by widhalmt** [comment]
I thought this is what the `cluster-zone` check is for? I want a check to see whether satellites in a zone are connected to each other. Both are in the same zone so I can not use cluster-zone.

**Comment by dnsmichi** [comment]
No, the `cluster-zone` check is a directional check from a parent to a child zone or vice versa. The `cluster` zone check takes all endpoints into account which are a) in the same zone b) the direct parent zone c) immediate child zones. That's why a filter on a specific zone would probably make more sense.

**Comment by widhalmt** [comment]
Ah ok. I know the `cluster-zone` check but misunderstood your last comment. ;-)

I think now I get what you mean. So I could run it with the filter "zone-x" on one satellite in zone-x and it would show me when the other satellite is not connected anymore?. And in addition run it on a host in "zone-y" with the filter to "zone-x" and I'd see if both satellites in zone-x are connected?

**Comment by dnsmichi** [comment]
Draw a picture please.

**Comment by widhalmt** [comment]
I will do so, please would you kindly remind me when we meet in person, next time? :-)

I just worked on the section in the Icinga 2 book about monitoring Icinga 2 HA and came back to realize that this would indeed be needed. I need to check from one satellite if it's sibling is still alive without receiving alarms whenever an agent goes offline.

**Comment by widhalmt** [comment]
After a little bit of chatting I think we found out what the other one was talking about :laughing: 

I need a "health check for highly available satellites". I need a check that shows when one of a pair of redundant satellites is offline.

 ### What we now have: ###
* A check (`cluster-zone`) that shows if at least one satellite in a redundant pair is connected
* A check (`hostalive`) that shows if a satellite is down
* A check (`cluster`) that shows if all configured endpoints are connected to a node.

### What we don't have: ###
* A way to check if one specific endpoint is not connected anymore.

### Why can't we use `cluster-zone`? ###

Because it will stay `OK` if at least one satellite is still connected.

### Why can't we use `cluster` in it's current implementation? ###

Because it will go `Critical` if at least one configured endpoint is disconnected. On satellites with hundreds or thousands agents to check this will be the case almost any given time.

### Can you draw me a picture? ###

Yes.

![ha-health check](https://user-images.githubusercontent.com/504849/38296927-2ff05f3e-37f3-11e8-87d0-62c60059984b.png)

**Comment by dgoetz** [comment]
Just my two cents: I see this as non critical state (read warning state) for the cluster_zone check if at least one but not all endpoints are online. Not sure if this would be easier to implement.

**Comment by widhalmt** [comment]
I think, @dgoetz 's idea could help us just as much as changing the `cluster` check. Both would be ok for me.

**Comment by dnsmichi** [comment]
I prefer an addition to the cluster check to "pin" it to the local zone. This requires enhancements to the ApiListener metrics, e.g. like this:

![screen shot 2018-04-18 at 12 28 10](https://user-images.githubusercontent.com/382049/38926801-2cead97e-4304-11e8-8938-9e0b9aadade6.png)

The `local_zone` values can then be used instead, if one says `use_local_zone` for the cluster check. I'm not sure about the naming, "local zone" is a somewhat internal term which would be exposed here.

**Comment by dnsmichi** [comment]
```
object Service "cluster-local" {
  check_command = "cluster"

  vars.cluster_use_local_zone = true

  host_name = "apitest"
  check_interval = 1s
  retry_interval = 1s
}
```

Check result could look like this:

![screen shot 2018-04-18 at 12 57 36](https://user-images.githubusercontent.com/382049/38928150-2e98131e-4308-11e8-8bd7-f83514a868a9.png)

**Comment by dnsmichi** [comment]
To be honest, I don't understand why changing the state from warning to critical would solve the issue with connection checks in the same local zone.

From what I discussed with @widhalmt, my conclusion is that this problem is about filtering away specific endpoints and only check whether the satellites in a HA zone are connected to each other, or not.
Such a thing cannot be checked with the `cluster-zone` check which is different to the `cluster` check. `cluster-zone` is direction dependant, execute on the master, checked on the satellite zone.

`cluster` instead allows to check the connectivity for a zone, and all directly connected parent and child zones. The culprit here is that a satellite zone always has a parent and likely a child zone for clients. If a client goes down, this has the same effect as if a satellite would go down (no differentiation on roles here). If the check turns NOT-OK because of this, you cannot say whether the HA-zone is not connected, or "just" a child zone client.

Therefore adding the option to only check a local zone with the cluster check is a way which preserves current setups, and adds the additional requirement for specific HA local zone checks. Applies to 2 and 3+ level scenarios.

**Comment by dnsmichi** [comment]
Same as #7466

**Comment by htriem** [comment]
Will be continued in #7466.
