### ISSUE TITLE
Icinga2 - Database cleanup option in IDOMysql configuration does not clean external command table

### ISSUE THREAD

**Issue by shellscriptcode** [Icinga/icinga2#5742]
version: r2.6.1-1 of Icinga2 have option cleanup for mysql and pgsql to clean up tables , and not manual cleanup of rows for Icinga2 tables. Could you please help me out , as i have followed all rules to clean my externalcommand table data more than 60d. Checkconfig of service goes well, Even restart of icinga2 goes well. But it does not clean up my old data than 60d for icinga2 external tables. Can you please advise when it will delete old rows ? I need to understand more .

Below is the configuration :
```
  cleanup = {
    downtimehistory_age = 48h
    contactnotifications_age = 31d
        externalcommands_age = 60d
  }
```

With this configuration and restart of icinga2 did not clean my table old rows , almost 190 million rows are present. This is production issue, and i am running as nonroot user safely as of now. Please suggest what i need to take care further in this. Your quick response is really appreciated.

**Comment by MaBauMeBad** [comment]
I think this post is from you, right ?

https://monitoring-portal.org/index.php?thread/42320-idomysql-cleanup-option-does-not-cleanup-tables-that-i-specified/

So, they are related.

**Comment by shellscriptcode** [comment]
Yes i asked question everywhere. 💯

**Comment by shellscriptcode** [comment]
Still waiting for somebody's reply

**Comment by shellscriptcode** [comment]
I want to know when icinga2 table cleanup will run once configured, and restarted icinga2?

**Comment by mcktr** [comment]
This is a issue tracker and not a ticket system, where you can expect a relatively fast answer based on SLAs. Asking every couple hours how the state of the issue is, will not help anybody. It takes some time to understand the issue, think about the causes and finding possible solutions for it. 

Please make sure that your database user has the necessary rights, you can find these information inside the documentation. 

AFAIK the Icinga 2 version 2.6.X is not supported anymore, please consider an upgrade to an more recent version and retest again.

**Comment by dnsmichi** [comment]
This isn't an enterprise support channel, but a bug tracker. Cross-posting and bumping issues is just rude. 

Continue in the linked thread and do your homework.

Regards,
Michael
