### ISSUE TITLE
Make the 'description' argument for command arguments (CheckCommand, ...) required

### ISSUE THREAD

**Issue by gunnarbeutner** [Icinga/icinga2#5799]

**Comment by Crunsher** [comment]
But why?

**Comment by lazyfrosch** [comment]
Please don't... That would be breaking

**Comment by dnsmichi** [comment]
For self documentation of the CheckCommands. It should at least log a warning when it is missing.

**Comment by Crunsher** [comment]
@dnsmichi Not a fan, it's an annoyance for anybody who creates their own CheckCommands and for the ITL we ought to just do it

**Comment by dnsmichi** [comment]
Do you have a better idea on how to enhance the documentation for those arguments?

**Comment by Crunsher** [comment]
If one wants better documentation, the responsibility lies with them. I have plenty of of self-written CheckCommands with arguments that don't have a description, because I know I don't need it. If it was a requirement I'd just put a space in there and what good would that be?

We shouldn't for someone to document her or his environment. icinga config lint as new feature? Sure. Mandatory -Wall for all? Nah.

**Comment by gunnarbeutner** [comment]
Whatever we come up with here should only really be enforced for the ITL commands by default. The basic idea is that - at some point - we'd be able to auto-generate the ITL documentation from the ITL .conf files.

**Comment by lazyfrosch** [comment]
Yes, but please let us handle this by linting the ITL.

My upcoming project in December/Januar is to migrate the ITL to its own repository / packaging logic.

This should include some testing and linting for config files, also testing them with `icinga2 daemon -C`

I'm assigning this to me and will provide details once there are any.

**Comment by lazyfrosch** [comment]
And yes generated docs are also on my plan

**Comment by lazyfrosch** [comment]
I guess we are consent about not requiring this :smile:
