### ISSUE TITLE
/var/spool/icinga2/perfdata is keeping all perf data

### ISSUE THREAD

**Issue by paladox** [Icinga/icinga2#5874]
## Expected Behavior

It to delete the files after maybe a day or a week?

## Current Behavior

It is keeping the files leading to storage problems at some point . rm -rf * would not even work do to the amount of files there. ls -la was also slow due to the amount of files.

I did not even realise it had that many files until i had storage problems (low storage).

It kept the files from when i setup icinga2 which was on june 23 2017.

And the files were 13gb worth. Deleting that freed storage up.

## Possible Solution

Delete files after a day or a week.

## Context

It was using up a lot of storage space

## Your Environment

* Version used (`icinga2 --version`):  r2.8.0-1
* Operating System and version: stretch and 9.3
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb statusdata
Enabled features: api checker command ido-mysql mainlog notification perfdata syslog
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by paladox** [comment]
it's creating too many files + it is doing it really fast.

If this is to keep performance data could there be a way to store less and without needing to create a new file everytime a check is run please?

**Comment by gunnarbeutner** [comment]
This is the intended behavior. You need to put some mechanism into place to pick those files up and delete them when they're no longer needed.

**Comment by guillaume-uH57J9** [comment]
The same issue hit a server here too. This cause an outage for services hosted on the same machine as icinga2. Hopefully we didn't put much services on the same host as icinga2. 

After some investigation we found inodes where exhausted on that machine's system partition. So while the partition had free space, no new file could be created due to lack of inodes. /var/spool/icinga2/perfdata contained ~ 550000 files. 

I trust that @gunnarbeutner is correct and perfdata is behaving as it should. 
Also I would kindly request to reopen as a Improvement/RFE (ie not a bug) to improve icinga2 ease of installation by disabling perfdata by default. 

The perfdata feature appears to be meant for users that put in place a custom processing of performance data files. If this is enabled but not custom processing is done, icinga2 will cause a system outage by using all available disk spaces, or inodes. 

If perfdata is only useful for those who put custom processing in place, I think disabling it by default would be a better balance: 
When putting in place custom processing, enabling the module is easy. However new users installing icinga2 for the first time will likly encounter issue if this is enabled by default, since they would expect icinga2 NOT to cause a system outage by installing it with the default setting.

**Comment by dnsmichi** [comment]
`perfdata` as a feature is disabled by default. There are some guides on the internet which wrongly suggest that you need to enable `perfdata` in combination with `influxdb` or `graphite` - our official documentation does not suggest that. 

So, in any case, if you actively enable the `perfdata` feature, you need to ensure that a collecting daemon is reading and purging the rotated files. If you don't have such, you need not enable this feature.

**Comment by guillaume-uH57J9** [comment]
@dnsmichi okay, that's reassuring. 

I'll double check with the colleague who installed it. If he can remember who told him to enable this, we'll request the guide to be fixed.
