### ISSUE TITLE
Vulnerability identified with INTEL / AMD processors. 

### ISSUE THREAD

**Issue by HCLTools** [Icinga/icinga2#5949]
Hi Team,

There is a new vulnerability identified at processor level that affects systems with INTEL / AMD processors. Some of the CVE numbers are – CVE-2017-5705, 5706, 5707, 5708, 5709, 5710, 5711, 5712.

Please check and let us know if this will have impact on Icinga

**Comment by dnsmichi** [comment]
Hi,

vendors (hardware and distributions) are preparing patches for their kernel, as the problem lies in hardware design, context switching and performance optimization. 

I do not really see how this relates to Icinga as a userland application here. If you're talking about the possible performance constraints one could encounter with a patched kernel, please test-drive that by yourself once vendor upstream released patches for your system. 

What's your real question behind listing these CVE numbers?

Best regards,
Michael

**Comment by Al2Klimov** [comment]
Firefox is also a userland app, but they've published a patch not to exploit this via JS. I2 has also an embedded language (and btw. all the check_plugins) – who knows what scary stuff you could do e.g. w/ bottom-up import...

**Comment by dnsmichi** [comment]
Bottom up import doesn't exist in 2.8. I'm looking for real use cases here, which cannot be resolved by waiting for vendor (kernel) updates.

Kind regards,
Michael

**Comment by Al2Klimov** [comment]
IMO just waiting for either OS or firmware upgrades (and installing them) would fix all possible attack vectors and apps like Firefox are just... "impatient".

**Comment by mcktr** [comment]
To my understanding the vulnerability depends on an very accurate time. The FireFox security fix just changes the resolution for some time sources or disables the ability to create such high-resolution timer objects. 

https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack/

For Icinga 2 I think it is best to wait for the vendor/kernel updates and see afterwards if there is something to do on our side.

**Comment by Crunsher** [comment]
Closing this in favor of #5990
