### ISSUE TITLE
Deprecate StatusDataWriter

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#6033]
We don't even support the classic ui anymore

**Comment by gunnarbeutner** [comment]
I'm all for this. Let's see what @dnsmichi thinks about it.

**Comment by dnsmichi** [comment]
That's the logical next step after kicking out the Classic UI, :+1 from me.

**Comment by JeKa0111** [comment]
With the deprecation of StatusDataWriter, may I ask what will replace status.dat? Currently, I have a script that reads that file to check if there are active downtime. So I was hoping to update my script before we migrate to 2.10.3. Thank you very much!

**Comment by dgoetz** [comment]
Such a question would be better asked in the community channels because more people will read it there and perhaps have similar scripts. 
But to answer your question there is a similar file with the `icinga2.state` (typically in `/var/lib/icinga2`) which is json(-like). An example how to handle it you can find at https://gist.github.com/lazyfrosch/f05b5cbfe8a05d4a1cee93db2c0028c0
But I would prefer the API or Database instead of any internal file. The API will gives you nice json and filter capabilies, the Database will also change in the future with IcingaDB replacing IDO so I would not base on it for now.

**Comment by dnsmichi** [comment]
That's an internal core file and not meant for user's access. Use the REST API to fetch runtime data from the core daemon. The state file also is subject to change in the future, with changed update frequency from now 5 minutes.
