### ISSUE TITLE
Windows Check check_network cannot be used with percentual thresholds

### ISSUE THREAD

**Issue by winter1967** [Icinga/icinga2#6155]
Out windows-admins wants  to be alerted, when the traffic of the network interfaces are reaching 90%.

So i read the help of the windows-check plugin "check_network":
-w THRESHOLD%
if the plugin accepts percentage based thresholds those will be used.
Does nothing if the plugin does not accept percentages, or only uses
percentage thresholds. Ranges can be used with "%", but both range values need
to end with a percentage sign.
All of these options work with the critical threshold "-c" too.

Ok.. it have done so:

c:\Program Files\ICINGA2\sbin>check_network.exe -c 99%
NETWORK CRITICAL 159674B/s | network=159674B;;99;0; 'Intel[R] Ethernet Connection I217-V_in'=117717B 'Intel[R] Ethernet Connection I217-V_out'=41957B

I expected, that the ouput were "ok", but i'ts critical, because the percent sign were disregarded.

Windows-Icinga-Agent Version is 2.8.1

**Comment by Crunsher** [comment]
The check_network does not know about the maximum throughput of the network. So your issue is actually two different ones:
A. We don't handle percentage based thresholds correctly when there is no max (ie percentage based can not work correctly)
B. We need to figure out the maximum throughput per network interface. AFAIK this can net be done using performance counters alone

**Comment by dnsmichi** [comment]
As discussed, this is a wontfix this time unfortunately.
