### ISSUE TITLE
Runtime attributes contain values of the current state in last_... variables

### ISSUE THREAD

**Issue by ekeih** [Icinga/icinga2#6302]
Hi,

I will try to explain our use-case to make it easier to understand the rest of the issue.
For different state changes we need different notifications in our setup:

1. **Ok -> Warning -> Ok:** No notifications at all
2. **Ok -> Critical -> Warning -> Ok:** Recovery Notification

For 2. we tried to implement the following condition in our notification script:

```
notification.type = RECOVERY AND
service.last_state = WARNING AND
service.last_state_critical > service.last_state_ok
```

Currently this does not seem to be possible (at least not in the way we expected). The runtime attributes in https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#service have confusing names:

- state: the new state
- last_state: the previous state

- last_state_ok, last_state_warning, last_state_critical: Based on the fact that *last_state* contains the previous state we assumed that the three *last_...* variables would contain the timestamp of the last state change BEFORE the current state change. But apparently the values already contain the current state change. (As a side effect the service.duration_sec is always very small (0.000767) in case of a recovery because it contains the number of seconds since the current state change. We would expect the time since the previous state.)

So during the **Warning -> Ok**-Change in 2. we have no way to access the timestamp of the last time that the service was ok.

So in my opinion the *last_...* variables should contain the timestamp of the last state change BEFORE the current state change. Or the `last_state` variable would have to contain the current state to be consistent with the other variable names.
Another option would be to improve the variable names and the documentation. This would not solve our use-case, but it would avoid confusion based on the different meaning of **last** in the variable names.

I hope my description is comprehensible. If not I will try to explain again ;)

(I guess the same applies to the host runtime attributes.)

## Your Environment
* Version used (`icinga2 --version`): 2.8.4
* Operating System and version: Ubuntu 16.04

**Comment by dnsmichi** [comment]
I've only read the requirements, which leads to the notification filter excluding the `Warning` state thus notifying only on `Critical` (and `OK` when it recovers).

What's wrong with that attempt and why bother with your own state history logic later on?

**Comment by ekeih** [comment]
Any thoughts about my last message? :)

**Comment by dnsmichi** [comment]
Sorry, this is one of those issues where I need time, pen and paper. I'm waiting for others to share their input meanwhile.

**Comment by ekeih** [comment]
No need to apologize, I will wait. Thanks for the confirmation that this issue is not forgotten. :)

**Comment by dnsmichi** [comment]
Might be a candidate for the OSMC hackathon.

**Comment by mauricemeyer** [comment]
> As a side effect the service.duration_sec is always very small (0.000767) in case of a recovery because it contains the number of seconds since the current state change. We would expect the time since the previous state.

In that specific use case, the service.duration_sec is not the metric we should use, as I think it to be „correct“ in the sense of naming. It tells you how long the service has been in the state it is currently in.

So it isn’t really useful for this issue with the `last_*` values not conforming to our expectations.

**Comment by Crunsher** [comment]
>Is this also needed for soft states?

Nah, that's not really helpful information. Checks may randomly fail once in a blue moon and we don't care about that.

>Does this make sense for the software?

We certainly want this for icingadb ^_^

**Comment by mauricemeyer** [comment]
Thanks for the feedback!

I’ll start implementing this next week.

**Comment by dnsmichi** [comment]
I trust your expertise on this since you've talked and discussed in person during the OSMC hackathon.
It also is a good idea to create new attributes which allow to keep the current known behaviour. If this turns well for a good reporting feature, I am all for it.

**Comment by mj84** [comment]
Alright, as suggested by @dnsmichi in #5533, I'm gonna explain my reporting situation a bit further.

In order to reliably determine SLA values (percentage of a timeframe, in which a monitored object was available) I am only interested in hard state changes, which are being populated by Icinga2 in the IDO table `icinga_statehistory`. (soft states don't account for non-OK states.)
Each entry in that table is associated with a monitored object and represents a state change.
It has a time stamp, some info about the current state and also if it is a hard state change, which needs to be accounted for.
Basically, I wrote a loop over all entries in a given time frame, and determine if the duration of a specific state needs to be considered for OK time or NOK time. (downtimes are being honored as well). At the end you do `OK seconds / Total seconds * 100 = availability` and that's it..

Currently (because of `last_hard_state` not behaving the way I expected it to :) ) I have to walk over *all* entries in a given timeframe (using a `for` loop), and manually check, if the previous state was a hard state, in order to calculate the amount of OK-seconds or NOK-seconds respectively.

So in order to reduce the complexity of said availability function, it would be very helpful to know the value of the last (previous) hard state. Then I could just do a select on all hard state changes and could calculate the duration of OK time or NOK time based on the values of the previous hard states.

**Comment by Thomas-Gelf** [comment]
It's good to see this discussion going on. However, to me it seems like different use-cases are trying to tackle a slightly related issue from a completely different perspective.

@mj84: this alone will not help you. This is not enough. You'll loose events. You might have no event in the chosen period. You might be forced to mix in events from before or after the chosen period or even the current object state to get a meaningful result. Downtimes might come into play, they might be considered "legal" SLA violations. Downtimes could be nested. Someone asks you to calculate Availabiliity only for specific time periods (weekdays, 9 to 5). Another one wants to "fix" an SLA afterwards because of <a-valid-reason>.

Believe me, for your use-case time dedicated to this issue will be wasted. I've been there before. With PostgreSQL pick a Cursor, jump from line to line, do your math. [here](https://github.com/Thomas-Gelf/icingaweb2-module-reporting/blob/master/schema/icinga_sla.sql) is a working example for MySQL/MariaDB. It doesn't address every weird scenario, but it isn't that bad at all. It needs to be written in a different way for PostgreSQL, but you can eventually steal some ideas.

Cheers,
Thomas

**Comment by mj84** [comment]
@Thomas-Gelf: Actually, my approach is kind of finalized and is being used productively in my environment for about 10 months with mostly monthly and weekly reports being generated.

I have implemented my PL/pgSQL function after inspecting the `icinga_availability` mysql function that exists in Icinga Reports 1.x.
I have taken care of some cases you mentioned such as when no state change occurs during a timeframe. Downtimes are considered as well, though I am not 100% sure about nested downtimes, currently nested downtimes might lead to a availability > 100%.
Sure, there is always the possibility that someone wants to fix an SLA by creating a downtime in the past, though that could be mitigated in Icingaweb2 / Icinga2 by disallowing downtimes to have a start date in the past.
Surely enough as well the complexity for SLA calculations knows no limits, I bet there is always some rare use case which invalidates any existing approach.
But for our (relatively) simple and straight-forward case with 24x7 SLA and check periods we found a solution in our custom Postgres function.
I surely will have a look at your MySQL example and the reporting module for icingaweb2, maybe I can provide input for a Postgres variant!

Cheers

**Comment by N-o-X** [comment]
@mauricemeyer you got any update on the implementation state? I would take that task, if you don't have anything laying around yet.

**Comment by mauricemeyer** [comment]
I have a cork in progress implementation with loads of debug output in my fork.

Work on it will continue on Monday as I’m currently on vacation.

**Comment by mauricemeyer** [comment]
I think I need some help with how to make it work for hosts, too - maybe I’m missing something or I can’t see the wood for the trees any more 🤔 

The change in my feature branch is working for services, but there’s something wrong when I try to apply this to hosts.

The current state (timestamps are not updated yet) can be [compared to the master](https://github.com/Icinga/icinga2/compare/75e06e9c0b5d7f776116df6742e33ef547c6a092...mauricemeyer:79d1aaac3cf1f97b0b4efd48d2bfb4863174b142) easily.

As you see, I added [the reset to OK on line 211](https://github.com/Icinga/icinga2/compare/75e06e9c0b5d7f776116df6742e33ef547c6a092...mauricemeyer:79d1aaac3cf1f97b0b4efd48d2bfb4863174b142#diff-22502b89a93b072e49bf234c3637b5a2R211) - but this does a hard coded reset to `ServiceOK`.

Will this also work for Hosts? I never really looked into host states as they always „just worked“ for me. My understanding is as follows:

The host derives its state from the check_command it uses. Therefore, this checkable is treated as a service that never appears to to user because the host wraps this „pseudo-service“.
Therefore, the host state is just an abstraction layer above a service.

Am I correct with this or did I get something fundamentally wrong?

**Comment by Crunsher** [comment]
Yes your assumption is correct, the host states are just wrapped service states. That means resetting the state to `ServiceOK` should work in both cases. I'd have to take a closer look as to why you are seeing incorrect states.

**Comment by mauricemeyer** [comment]
Okay, thanks for that info. I will debug this again next week to find out if I’m just misreading something or if it’s an actual error.

**Comment by mauricemeyer** [comment]
I have tested some more and it looks like defining my test check as `check_command` does exactly nothing.

Can somebody please have a look at/test [my current implementation](https://github.com/mauricemeyer/icinga2/tree/feature/worst-state) and tell me if I just failed to setup my test environment correctly or if there is really an issue?

**Comment by dnsmichi** [comment]
Imho that's implemented with previous_hard_state etc. coming with 2.12 for IcingaDB.
