### ISSUE TITLE
Execute Host Check before Service Notification

### ISSUE THREAD

**Issue by cycloon** [Icinga/icinga2#6447]
Icinga 2 should execute a Host Check before a Service notification is issued to prevent unwanted service notifications when a host is going down.

If you take into account that all of the following is true:
- service has a dependency for its host
- when rebooting a host, services usually go down before host
- you don't want a service notification if you shortly after get a host notification

Then icinga2 is impossible to manage a configuration where it is really save to prevent service notifications if host is down. I know you can come close if you change the check interval and the retry interval of hosts and services, but this would either mean, I add lots of load to the server (change host check intervals to 1 minute) or I get notified for real service problems more lately (change service retry to 5)

What we really should be able is what Nagios did before: If you are about to send a service notification, first issue a host check and make sure it is not DOWN. That way you can really assure that you don't get unwanted service notifications.

We currently get tons of false service notifications if we issue a centralized update at night and 20 hosts are rebooting their operating system.

## Expected Behavior
Icinga should not send service notifications if a host check would show the host is down at that moment.

## Current Behavior
Icinga only checks the current state of the host wich could be minutes too old. This results in first issuing some of the service notifcations and then issuing host down notifcations some time later.

## Possible Solution
Execute the host check before issuing service notifications.

## Steps to Reproduce (for bugs)
1. Host with check_interval = 3m and retry_interval=1m and max_check_attempts=3
2. Service with check_interval = 3m and retry_interval=1m and max_check_attempts=3

## Your Environment
* Version used: r2.9.0-1)
* Operating System and version: Debian 9
* Enabled features: api checker command compatlog ido-mysql livestatus mainlog notification statusdata

**Comment by dnsmichi** [comment]
There's no synchronous wait for an on-demand host check, the service check depends on the host check itself being fired in a more frequent interval to properly detect such a dependency state. This has been discussed quite often on the community channels, and lowering the *_interval for the host checks turned out to be the most effective.
There won't be effort soon to implement the asked scenario, also since this will block check execution, or might run into troubles with HA enabled zones where the service is checked on the left side, whereas the host is checked on the right side. As said, choose the workaround mentioned above.
