### ISSUE TITLE
check_update thresholds ignored

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga2#6541]
Commit 0c006637ea2aa95faeb4d48f212fd4159d44fae3 makes check_update ignore the command line parameters controlling the thresholds, I have not reproduced this yet but it seems to me any update requiring a reboot will yield CRITICAL no matter if `--critical` is set.

This has been discovered [here ](https://monitoring-portal.org/t/unable-to-disable-the-warn-crit-for-service/3654).

**Comment by mcktr** [comment]
I am a bit confused how the threshoulds should actually work:

* If `--warning` is set to `true` or `1` we return warning if there are important updates 
* If `--critical` is set to `true` or `1` we return critical if any of the important updates requires a reboot

Am I correct so far? 

Anyhow this issue should be addressed with #6480 since the PR introduces actual threshoulds e.g. return a warning/critical state if there are 10 updates available. But the behavior remains, the check will always return critical if an available update requires a reboot, therefore #6480 implements a new parameter `--no-reboot-critical` to ignore the requires reboot state.

I'll take this into account testing #6480.
