### ISSUE TITLE
Servicegroup example is wrong

### ISSUE THREAD

**Issue by tkoeck** [Icinga/icinga2#6550]
The ServiceGroup example at

https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#servicegroup

seems to be wrong.

Shouldn't there be an 'assign where' clause somewhere?

**Comment by mcktr** [comment]
Not necessarily. It is valid that you can define a service group without the `assign where` statement, this will create a service group without any services as members in the first place. Now you can use the `groups` attribute in your service object to define to which groups the serivce belongs. Have a look into the service object example: https://www.icinga.com/docs/icinga2/latest/doc/09-object-types/#service this will make it more clear. 

It is best practice to use the `assign where` statements to assign groups, as the hint already tells.

Since the documentation and the statemen ist correct I'll close here.
