### ISSUE TITLE
Add function get_object_exist to DSL

### ISSUE THREAD

**Issue by lbetz** [Icinga/icinga2#6659]
I'd like to check if an object is configurated. 

## Expected Behavior
My motivation for this function is to check if an agent is installed. That can be done by looking for an object of type endpoint with the same name as the host itself.

When there is an endpoint object I wanna check via command endpoint bridge and on the other hand I wanna perform the plugin execution by ssh.

```
apply Service "load" {
  ...
 check_command = "load"
 command_endpoint = host.name
 assign where get_object_exist("endpoint", host.name) && vars.os == "Linux"
}

apply Service "load" {
 ...
 check_command = "by_ssh_load"
 assign where !get_object_exist("Endpoint", host.name) && vars.os == "Linux"
}
```

## Current Behavior
At the moment I use get_object instead but this function is very expensive, I think because I get a full copy of the object.

## Possible Solution
A function that return a boolean, true if the object exist otherwise false.

**Comment by dnsmichi** [comment]
Likely we don't need it, since I've just seen that you'll get a ConfigObject::Ptr in the background where Icinga just copies a reference which is immediately cleared away with no return value assigned.

The main problem would be the order of objects here in static objects, for apply rules this should work just fine.

**Comment by lbetz** [comment]
top.
