### ISSUE TITLE
Intended semantics of last_hard_state

### ISSUE THREAD

**Issue by efuss** [Icinga/icinga2#6688]
I'd usually be asking something like this on a developer's mailing list, but was told by a core developer he regarded that list as dead and preferred GitHub. I hope I haven't mistaken him.

I would like to know what the intended semantics of `last_hard_state` are.

Please note that I'm _neither_ asking what the documentation says (which is essentially nothing) _nor_ what the name suggests to you (which is abgigious as pointed out below) _nor_ what the current code does. I'd like to know what exact behaviour is regarded as most beneficial.

The only evident case is the transition Hard-Foo -> Soft-Bar. You surely want Foo as `last_hard_state`; this is the whole point of it. Transition Hard-Foo -> Soft-Foo is impossible.

For Soft-Foo -> Soft-Bar (or -> Soft-Foo) you surely don't want to touch it.

For Hard-Foo -> Hard-Foo there's most certainly no point in touching it.

This leaves us with two open cases:

1. Hard-Foo -> Hard-Bar. You may vote for Bar, since that's the last hard state in the sense of the most recently acquired state that is hard; you may vote for Foo, since that's the last hard state in the sense of the hard state previous to the current one.

2. Soft-Foo -> Hard-Bar (or Soft-Bar -> Hard-Bar). You may expect Bar, because that's the most recent acquired state being hard; you may expect no change since you can get that information from the current state and would lose information if you overwrite last_hard_state.

The current code also, in case of a volatile checkable, sets `last_hard_state` to the currently acquired state, even if that's a soft one (!). Does that make any sense?

**Comment by mauricemeyer** [comment]
As @ekeih said, this is related to #6302. There’s currently two things I know of that where you will use the variables in:

1. To display a short history of the alert, something around the lines of „this service was critical for 15 days, then went warning 4 days ago and is now OK again“. For that, you will vote for **bar** in your first example.
2. For notifications in specific cases.
 We alert certain users only for CRITICAL states. If the state then changes to WARNING and then to OK, there is no possibility for that user to get a RECOVERY, because we can’t check this currently. So there, you would vote **foo**.

You can’t fit both of that in one running icinga2, obviously. I will propose a solution for our notification case in #6302 very soon (still need to work out the details).

I think that that the **current behaviour is the most beneficial**, as it is the technically correct behaviour by the naming of the variables (and enables you to do what my first example describes).

**Comment by N-o-X** [comment]
Should be fixed with `previous_hard_state` since 2.12.0. If you still think something is missing here, please feel free to reopen this issue.
