### ISSUE TITLE
Incorrect timestamp since time change (Nov 4th 2018)

### ISSUE THREAD

**Issue by mzac** [Icinga/icinga2#6765]
Since we changed from EDT (-4) to EST (-5) I have been noticing time issues show up in Icinga.  On two of my servers, a simple restart of Icinga was able to fix it and times showed up correctly again, however one dev server I have now refuses to show the correct time even after restarting Icinga.

## Expected Behavior

Icinga2 should be reading the current localtime and putting the correct time either with UTC or epoch in the database and should not require a restart when a time change happens.

## Current Behavior

The times displayed in Icinga are off by 1 hour

```
root@black:/etc/icinga2/conf.d# date
Sun Nov 11 20:41:30 EST 2018
```

Before restarting Icinga2:
![image](https://user-images.githubusercontent.com/10270879/48322086-ba499c00-e5f3-11e8-8a0f-83ff95331604.png)

After restarting Icinga2 you can see the startup time is still off:
![image](https://user-images.githubusercontent.com/10270879/48322096-c7ff2180-e5f3-11e8-8a79-4f548cbdfbb9.png)

## Possible Solution

Icinga should be tracking system time changes.  I am seeing the issue on both 2.9 and 2.10 installs on Redhat and Ubuntu alike.

## Steps to Reproduce (for bugs)

Set a computer's date and time before the Nov 4th time change (2am becomes 1am), and let the clock roll back 1 hour while Icinga is running and see if the issue shows up.

https://www.timeanddate.com/time/change/canada/montreal

## Context

All event times are off by 1 hour

## Your Environment

* Version used (`icinga2 --version`): r2.10.1-1
* Operating System and version: Ubuntu 18.04.1 LTS
* Enabled features (`icinga2 feature list`): checker command ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.6.1
* Config validation (`icinga2 daemon -C`): All good

**Comment by dnsmichi** [comment]
Icinga 2 uses UTC by default, your report only shows views from Icinga Web 2. Please verify that the data written and stored in your database is correct.

Icinga 2 also detects when there are time jumps involved and adjusts its timers accordingly. Otherwise daylight saving time adjustments would never work. You'll see such a message inside the log, something like `Application: We jumped forward/backward in time: 37.09 seconds`.

https://github.com/Icinga/icinga2/blob/master/lib/base/application.cpp#L312

**Comment by dnsmichi** [comment]
Closing for the lack of feedback.
