### ISSUE TITLE
Node wizard doesn't perform auto-signing on not actively connecting satellite

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga2#6767]
## Expected Behavior

Node wizard performs auto-signing anyway.

## Current Behavior

Node wizard doesn't perform auto-signing on not actively connecting satellite.

## Possible Solution

Perform auto-signing anyway and let the user choose the PKI master (as e.g. in v2.6).

## Steps to Reproduce (for bugs)

https://youtu.be/rZc8NPCT-as?t=362 (about 1,5 minutes)

## Context

#6766

## Your Environment

The latest bleeding edge hipster stuff, see [the Vagrantfile](https://youtu.be/rZc8NPCT-as).

**Comment by dnsmichi** [comment]
Please provide the steps to reproduce in text form, videos are nice but take away attention from the real problem.

As of now I'm not really sure if I understood the problem, but let's try it.

1) You've chosen that the client won't actively connect to the satellite.

Vice versa, this means the satellite establishes the connection. 

2) Therefore the node wizard cannot talk to the parent host and lets you verify the presented CA certificate, nor is it possible to do any immediate certificate signing request.

In order to prove the validity of the setup, you have to manually copy the public ca.crt certificate file from your parent node to the client, and then restart Icinga 2. Then the (auto-)signing procedure kicks in just like before - when the satellite actively initializes the first connection.

Anything else with different connections for pki requests and actual endpoint connections adds more complexity and is outside of the scope for this CLI helper tool. As of v2.8, we've designed this for the CA proxy, so it is not really comparable to older versions anymore. Especially not with the requirement of asynchronous signing requests with 3+ cluster levels.

Closing for the mentioned reasons.

**Comment by Al2Klimov** [comment]
That 1.5m video part is a collateral damage from the video recording for #6766 and a proof that I've not overseen any elephant. Anyway my "problem" is that sat1 *could* connect to master2, but *should not* for the sake of *check now* (see also #6766 and https://github.com/Icinga/icinga2/issues/6234#issuecomment-437879522).

The *parent node* is not neccessarily your *PKI master* and because of that v2.6 have asked me for the *PKI master* explicitly. v2.10 still performs auto-signing, but only if the given node shall actively connect to its parent which is assumed to be the *PKI master* – which is not true e.g. in my actual private cluster with only 2 levels.

But if you say that it's a design decision and auto-signing is that easy since v2.8 – OK.
