### ISSUE TITLE
Selinux denials if sudo is used within a check since https://access.redhat.com/errata/RHEA-2018:3199

### ISSUE THREAD

**Issue by apollo13** [Icinga/icinga2#7039]
## Expected Behavior

Executing sudo (given a valid sudoers configuration) in a check should work.

## Current Behavior

Fails with the following audit log:

```
type=USER_AVC msg=audit(1553101636.560:106902): pid=850 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.5611 spid=863 tpid=2467 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:system_r:nagios_unconfined_plugin_t:s0 tclass=dbus  exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'
```

## Possible Solution

Since a sudo update in Centos 7, `/etc/pam.d/sudo` includes `system-auth` which in turn activates `pam_system`:
```
* Fri Sep 21 14:00:00 2018 Daniel Kopecek <dkopecek@redhat.com> 1.8.23-2
- RHEL-7.6 erratum
  Resolves: rhbz#1533964 - sudo skips PAM account module in case NOPASSWD is used in sudoers
  Resolves: rhbz#1506025 - Latest update broke sudo for ldap users.
  Resolves: rhbz#1502630 - inclusion of system-auth for session hooks missing in sudo PAM snippets
```
Now this means that `pam_systemd` tries to talk to dbus which is not allowed - resulting in long timeouts and the check getting killed at some point.

I have fixed this locally by adjusting the policy like this:
```
module icinga 1.0;

require {
	type systemd_logind_t;
	type nagios_unconfined_plugin_t;
	class dbus send_msg;
}

#============= systemd_logind_t ==============
allow systemd_logind_t nagios_unconfined_plugin_t:dbus send_msg;
```

## Steps to Reproduce (for bugs)
1. Use an up2date centos 7.
2. Configure sudoers to allow execution for the nagios user
3. Execute a check and inside the check itself call sudo
4. See the lovely avc message

**Comment by dgoetz** [comment]
Thanks for your report, but after looking into it, I came to the conclusion this should be addressed in the policy provided by Red Hat.

My reasons for this are:
- Domain `icinga2_t` is not involved here.
- The only plugin policy managed in this policy module is `nagios_notification_plugin_t`.
- In this case it works partially because of being `nagios_unconfined_plugin_t` (the unconfined one). If it would be a different type already sending the message to dbus would fail. So it would be solved best if `nagios_plugin_template` in nagios.if would contain `systemd_dbus_chat_logind(nagios_$1_plugin_t)`
- Another option would be a new type being introduced for running sudo in the plugin which I do not want to maintain.

But I will look into allowing `sudo /path/to/plugin` as I found this also not working.

**Comment by apollo13** [comment]
> should be addressed in the policy provided by Red Hat.

Which policy are we talking about? I'll see if I can report this to redhat then.

> But I will look into allowing sudo /path/to/plugin as I found this also not working.

Ah yes, that one also runs into denials

**Comment by dgoetz** [comment]
> Which policy are we talking about? I'll see if I can report this to redhat then.

I am not sure if it is part of Red Hat's patches to the reference policy or of the reference policy itself, but Red Hat will know it. All policy versions are build from the same source so filing the issue against `selinux-policy` should be good.

**Comment by dgoetz** [comment]
> Ah yes, that one also runs into denials

I bumped the policy version to include a new boolean `icinga2_run_sudo`. It is disabled by default, but I hope including the error message you should get in the docs will make people (or google) find it anyway.
