### ISSUE TITLE
Windows Agent Wizard: Evaluate which .NET framework is required

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga2#7090]
## Describe the solution you'd like

Right now, we'll need .NET 2.0 provided by .NET 3.5, requiring an additional package during installation. Modern systems already provide 4.6.1 and newer.

Current target platforms:

- Server 2016/2019
- 10

Also, evaluate whether we can enhance the version getter with the new required OS versions.

## Additional context

- Windows Server 2012 was EOL on 9.10.2018: https://support.microsoft.com/de-de/lifecycle/search?alpha=windows%20server%202012
- Windows was EOL'd on 9.1.2018: https://support.microsoft.com/de-de/lifecycle/search?alpha=windows%208

**Comment by mcktr** [comment]
Please keep in mind that Windows has extened support:

| OS | Extended Support until |
|---|---|
| Windows Server 2012 | 10.10.2023 |
| Windows Server 2008 R2 with SP1 |14.01.2020 |
| Windows 8.1 | 10.01.2023 |
| Windows 7 with SP1 | 14.01.2020 |

The minimum default .NET version on the various Windows version can found be here: https://blogs.msdn.microsoft.com/astebner/2007/03/14/mailbag-what-version-of-the-net-framework-is-included-in-what-version-of-the-os/

We can at least expect .NET 3.5.1.

**Comment by dnsmichi** [comment]
I don't see _extended_ Enterprise support as one of our major priorities, same discussion as with SLES 12 SP2 LTSS. If you'll need a more modern .NET framework from MS, you should truly get it, and we can require it. 

https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements

OS                      | .NET preinstalled
----------------|-----------------------------
Windows 10       | 4.6
Server 2016       | 4.6.2
Server 2019       | 4.7.2

All other versions can install .NET 4.6 or 4.7 as they prefer, so not an issue.

**Comment by mcktr** [comment]
The extended support in Windows is slightly different. Microsoft supports an operating system for at least 10 years (5 years mainstream support followed by 5 years extended support). The extended support is not limited on enterprise customers, every Windows user with a supported OS will gain the extended support. During the extended support Microsoft stops publishing feature updates and only security updates are available. A paid support model is available even after the end of the extended support. 

https://support.microsoft.com/en-us/help/14085/fixed-lifecycle-policy

I was a bit worried that the newer .NET versions are not (officially) supported on the older Windows versions, but according to the link and list you provided this is not an issue and we can expect a modern .NET framework. :+1: 

AFAIK we currently do not check if the required .NET version is installed, do we? When we change the required .NET version we should implement such. I have prepared a patch locally which checks if a given .NET framework is available prior the installation process, once a decision is made on which .NET version we use in the future I can create a PR for this.

**Comment by dnsmichi** [comment]
The only thing I know is that we link against .NET 2.0 inside the C# parts for many years. I want to avoid this dependency - meaning to say, if a user goes for Server 2016, there shouldn't be the requirement to install .NET 3.5 providing 2.0 when .NET 4.6 is sufficient.

Highly likely this is a small subtle change with the transition from VS2015 to VS2017 already, or somewhere hardcoded in the csproj file.

**Comment by mcktr** [comment]
The C# are built in .NET 2.0. But we set the supported .NET version to 2.0 and 4.0 (which includes everything above 4.0 as well). 

https://github.com/Icinga/icinga2/blob/2b3511d8a6942909958f7d7944fb806776cd261b/agent/windows-setup-agent/App.config#L2-L7

By doing this it is not necessary to install .NET 3.5 (with 2.0) on a Windows that comes with .NET 4.x.x. I tested the snapshot package on a freshly Windows 10 and I don't need to install .NET 3.5 (with 2.0), the Agent Wizard worked without it.

But as long as we develop on the .NET 2.0 basis developers need to install the .NET 3.5 (with 2.0) package, since the targeted .NET version is 2.0.

* https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility
* https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/startup/supportedruntime-element

**Comment by dnsmichi** [comment]
Ah, ok, thanks for the analysis. So we need to "re-do" the wizard with a more modern .NET version. That being said, based on the previous analysis, I'd expect .NET 4.6 a sound basis for this in the future. Can you estimate how much effort this will be? I'm thinking about adding that as a trainee project for @htriem in the next months.

**Comment by mcktr** [comment]
Changing the target .NET Framework seems to be quite simple, as long as we don't have references to a different version of the .NET Framework . From what I found out we dont have that much references: 

* `System`
* `System.Data`
* `System.Drawing`
* `System.ServiceProcess`
* `System.Windows.Forms`
* `System.Xml`

Visual Studio should change change the references automatically to the newer version, but it may happen that some needs to be updated manually. But since the mentioned references are all build in into .NET I don't expect big problems here. 

Once the target .NET version is changed to a modern one, we should modify the installation wizard and check if the .NET Framework is present. Since we already build the Windows package with WIX we can use the extension `WixNetFxExtension` to accomplish this.

If this does not become a trainee project, you can assign this to me.

Three articles concerning the topic:

* https://docs.microsoft.com/en-us/visualstudio/ide/how-to-target-a-version-of-the-dotnet-framework?view=vs-2019
* https://docs.microsoft.com/en-us/visualstudio/msbuild/troubleshooting-dotnet-framework-targeting-errors?view=vs-2019
*http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/check_for_dotnet.html

**Comment by dnsmichi** [comment]
If you're faster and would like to do it, go for it. We always can find more tasks for Henrik after all :-)
