### ISSUE TITLE
Event handlers fire from both master and satellite

### ISSUE THREAD

**Issue by blakehartshorn** [Icinga/icinga2#7141]
## Description:
When a remote check_command fires (that is, not from a client endpoint), it will only fire in the relevant zone, but event commands will fire on a satellite and a master in satellite zones. This is one node per satellite and master zones; it does not trigger on multiple servers and does not bleed into other zones. Troubleshooting was done here: https://community.icinga.com/t/event-command-firing-from-both-master-and-satellite/978/7

## To reproduce:
Create a basic check command and event command for a satellite zone, and execute without a designated endpoint.

## Your Environment
* Version: 2.10.4
* 2 masters, 2 satellites per satellite zone

## Additional context
Object of an afflicted check:
```
Object '[hostname]!test relationship' of type 'Service':
  % declared in '/etc/icinga2/zones.d/global-templates/testing.conf', lines 11:1-11:33
  * __name = "[hostname]!test relationship"
  * action_url = ""
  * check_command = "test-relationship"
    % = modified in '/etc/icinga2/zones.d/global-templates/testing.conf', lines 13:3-13:37
  * check_interval = 300
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.conf', lines 78:3-78:21
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "test relationship"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = "test-event"
    % = modified in '/etc/icinga2/zones.d/global-templates/testing.conf', lines 14:3-14:30
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "[hostname]"
    % = modified in '/etc/icinga2/zones.d/global-templates/testing.conf', lines 11:1-11:33
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 5
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.conf', lines 77:3-77:24
  * name = "test relationship"
    % = modified in '/etc/icinga2/zones.d/global-templates/testing.conf', lines 11:1-11:33
  * notes = ""
  * notes_url = ""
  * package = "_etc"
    % = modified in '/etc/icinga2/zones.d/global-templates/testing.conf', lines 11:1-11:33
  * retry_interval = 30
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.conf', lines 79:3-79:22
  * source_location
    * first_column = 1
    * first_line = 11
    * last_column = 33
    * last_line = 11
    * path = "/etc/icinga2/zones.d/global-templates/testing.conf"
  * templates = [ "test relationship", "generic-service" ]
    % = modified in '/etc/icinga2/zones.d/global-templates/testing.conf', lines 11:1-11:33
    % = modified in '/etc/icinga2/zones.d/global-templates/templates.conf', lines 76:1-76:34
  * type = "Service"
  * vars
    * notification
      * [internal notification group]
        * mail = true
          % = modified in '/etc/icinga2/zones.d/global-templates/templates.conf', lines 81:5-81:37
  * volatile = false
  * zone = "lassatellite"
    % = modified in '/etc/icinga2/zones.d/global-templates/testing.conf', lines 11:1-11 
```

**Comment by b33rcity** [comment]
I've also run into this issue recently and have an additional data point I find interesting.

In my case, the event handler passes `$check_source$` to a script which runs MTRs to the target host. `check_source`'s value appears in a Slack message to help identify where a problem is coming from. MTR, of course, shows the origin hostname in its output, as well.

The event handler runs on the satellite and the master at roughly the same time, and I get two separate messages. However, both say that they are from the satellite--i.e., `check_source` is the satellite even when the handler is being run on the master. This does make some sense, since the satellite _is_ the source of **check**Commands. 

What was really odd about it was that when I pulled up the IDO in mysql and queried the `icinga_eventhandlers` table, all of the recorded event handlers came from the master. (Also the commandline fields were NULL on every record, but that's a separate issue.) So the satellite event handlers are not being recorded at all. Maybe that's how it's supposed to be, but I found it surprising. 

Version info
```
# icinga2 -V
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.4-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: 602f071dcede
```
Master zone config
```
object Endpoint NodeName {
  host = NodeName
}
object Zone "master" {
  endpoints = [ NodeName, ]
}
object Zone "EU" {
    endpoints = [ "eu.example.com" ]
    parent = "master"
}
object Endpoint "eu.example.com" {
   host = "10.10.10.10"
}
object Zone "global-templates" {
	global = true
}
```
Satellite's zone config
```
object Endpoint "<master's Nodename>" {
}
object Zone "master" {
	endpoints = [ "<master's Nodename>" ]
}
object Endpoint "eu.example.com" {
}
object Zone "EU" {
	endpoints = [ "eu.example.com" ]
	parent = "master"
}
object Zone "global-templates" {
	global = true
}
```
The EventCommand is defined in global-templates.

The Host object has `event_command` set via its template, and the only Service object attached to it does not have any `event_command` set. The Service and the Host Template are defined in global-templates, and the Host is defined in the satellite's zone directory.

**Comment by dnsmichi** [comment]
Event handlers are called whenever a cluster instance processes a check result locally. There is no synchronisation for additional event handler history logging in place, i.e. you won't see satellite or client event handler calls in the master's history log in DB IDO or the API events. That's on purpose as this generates huge network traffic overload - typically unneeded. Neither does the DB IDO feature populate the database table by default, as this information isn't needed in Icinga Web 2.

If you're planning to look into the underlaying problems and code, feel free to do so. No-one of the core devs will take anytime soon.

**Comment by htriem** [comment]
There are no plans to change behaviour as @dnsmichi pointed out. Closing.
