### ISSUE TITLE
check_interval and retry_interval in thruk using livestatus as backend

### ISSUE THREAD

**Issue by chrnie** [Icinga/icinga2#7402]
## Describe the bug
There is a configuration overview in thruk showing all configured attributes for hosts and services (like in the old icinga classic UI).
It's not possible at the moment to see check_interval or retry_interval. 

I'm sure there is an interval configured.

## To Reproduce
As Thruk is using livestatus as backend, we talked to @sni to ask him if he could fix it. It seem's the bug is inside icinga2's livestatus implementation.
It's possible to reproduce the bug usings livestatus commands:

```
echo -e "GET services\nColumns: host_name description check_interval retry_interval\nFilter: description = lx-disk\nFilter: host_name = censored_hostname\n" |nc -U /path_to_/var/run/icinga2/cmd/livestatus
censored_hostname;lx-disk;5;1

echo -e "GET status\nColumns: interval_length\n" | nc -U /path_to_/var/run/icinga2/cmd/livestatus
0
```
So the bug comes from interval_length = 0

## Expected behavior
I'd like to see the real interval, therefore interval_lenght should be set.

## Screenshots
![livestatus_interval_thruk](https://user-images.githubusercontent.com/7256939/62608028-60b29b80-b8ff-11e9-85f6-22a56568226f.png)

## Your Environment

icinga2 version: 2.8.5
OS: RHEL 7
icingaweb2: False
thruk: 2.2.2
config_validation: True

## Ref
Thruk: check intervals in icinga2 livestatus ref/NC/628339

**Comment by dnsmichi** [comment]
Well, would be easy to fix in the web application since it already knows that the backend is icinga2 and not use the 1.x legacy divider. This worked very well with the now deprecated classic UI too.

Anyhow, if thruk is not willing to fix this, it has to wait after 2.11 is released. What's the expected value for `interval_length` by thruk if `check_interval` is dumped in seconds?

**Comment by chrnie** [comment]
The value in check_interval and retry_interval seems to be dumped in minutes. So it should be 60.

**Comment by sni** [comment]
If `check_interval` and `retry_interval`is in minutes, then it should return 60. Basically `interval_length * check_interval` should reflect the configured interval in seconds. Naemon returns 60 by default, because intervals are usually configured in minutes. If icinga2 uses seconds, then it should return 1.
I cannot fix that in Thruk, it is an issue in icinga2 livestatus. Sure, I could add another workaround for icinga2, but i guess it would be better to fix it in icinga2 once and for all.

**Comment by sni** [comment]
btw, this issues comes from a (hopefully paying) netways customer.

**Comment by dnsmichi** [comment]
Mhm, the time will come when this feature gets deprecated, so the fix is ugly like the rest.

**Comment by sni** [comment]
> Mhm, the time will come when this feature gets deprecated, so the fix is ugly like the rest.

Is this decision final already and is there a schedule for this?

**Comment by dnsmichi** [comment]
No final decision yet.
