### ISSUE TITLE
fedora 

### ISSUE THREAD

**Issue by naschidaniel** [Icinga/icinga2#7440]
Adding ICINGA-RPM to Fedora dnf leads to this result.

[FAILED] icinga-rpm-release-29-latest.noarch.rpm: Curl error (7): Couldn't connect to server for https://packages.icinga.com/fedora/icinga-rpm-release-29-latest.noarch.rpm [Failed to connect to packages.icinga.com port 443: Connection refused]

My Server IP: 134.209.228.249
My Fedora is hosted on DigitalOcean

on my lokal machine the installation works

thanks for your help

**Comment by naschidaniel** [comment]
it looks like that i hase something to do with my upgrade from 28 to 29

**Comment by Al2Klimov** [comment]
Hello @naschidaniel and thank you for reporting!

* Is that IP being assigned statically or dynamically?
* Since when that IP is assigned to your server?
* When did the error occur (date and time)?
* Are you sure that machine hasn't ever been misused for a DDoS attack?
* Please could you re-try installing/upgrading?

Best,
AK

**Comment by b0e** [comment]
Please try again! We struggle with some DDoS including your Digital Ocean Network. Your IP shouldn't be blocked any more.

**Comment by naschidaniel** [comment]
perfect, it worked!
Thanks for your support.
All the Best

**Comment by naschidaniel** [comment]
perfect, it worked!
Thanks for your support.
All the Best
