### ISSUE TITLE
Icinga2 feature list is not exact on "icinga2 feature list" (only checked on Windows)

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icinga2#7446]
## Describe the bug
If you comment out the "include "features-enabled/*.conf" like the Powershell agent script does, "icinga2 feature list" shows "checker" as enabled even if its not.

## To Reproduce
1. Comment out "include "features-enabled/*.conf" in icinga2.conf.
2.  Restart the service
3. check "icinga2 feature list" 

## Expected behavior
read the configfile and interpret it.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): icinga2.exe - The Icinga 2 network monitoring daemon (version: v2.10.5)
* Operating System and version: Windows Server 2016 Datacenter
* Enabled features (`icinga2 feature list`): does not shows the correct values ;-)

**Comment by dnsmichi** [comment]
That truly is a problem with the Powershell script not following our proposed way of doing things here. `icinga2.exe feature <action>` is the only recommended and supported way of configuring the features. 

My proposal to change this in the PS module was rejected a while ago: https://github.com/Icinga/icinga2-powershell-module/issues/52

For newer versions, this is on the roadmap to be improved. @lippserd @bobapple highlighting you so that you'll know about this (imho) mandatory change.

**Comment by dnsmichi** [comment]
That's taken into account with the new Icinga for Windows framework announced here: https://icinga.com/2019/11/05/icinga-for-windows-rc-available/
