### ISSUE TITLE
Incorrect reporting of zone disconnects by services

### ISSUE THREAD

**Issue by acid-eater** [Icinga/icinga2#7475]
## Describe the bug

When Icinga2 is shut down on a satellite no problems are reported in Icingaweb2 unless you have a "cluster-zone" check in place, which is the correct and expected behavior.

But if you shut down Icinga2 on a Windows-client that is attached to that very same satellite Icingaweb2 shows "not connected" messages for every service running on that client.

## To Reproduce

1.  Create a master ("A-SRV" in zone "master") on a Linux system
2.  Create a satellite ("B-SRV" in zone "sat", parent="master") on a Linux system
3.  Create a client ("C-SRV" in zone "client", parent="sat") on a Windows system
4.  Define one check each for the satellite and the client (for example "apt" for the satellite and "disk-windows" for the client, make sure "command_endpoint" is correct)
5.  Observe that everything is okay in Icingaweb2
6.  Shut down Icinga2 on the satellite
7.  Observe that there are no errors, warnings etc. in Icingaweb2 (but notice that the checks no longer run, "Next check" becomes negative)
8.  Start Icinga2 on the satellite again
9.  Repeat step 5 (give it a moment...)
10. Shut down Icinga2 on the client (stop the Windows service)
11. Observe Icingaweb2 reporting "not connected" for the "disk-windows" check on the Windows client (exact message: "Remote Icinga instance 'C-SRV' is not connected to 'B-SRV'")
12. Start Icinga2 on the client again (start the Windows service)
13. Repeat step 5

Repeat steps 5 through 13 as often as you like, it will always happen

## Expected behavior

Services in disconnected zones should not report that their zone is disconnected, it is the responsibility of the Icinga2 admin to ensure proper loss of connectivity reporting by using "cluster-zone" checks and generate alarms accordingly. It is the responsibility of the monitoring team to define downtimes in order to avoid false-alarms by these "cluster-zone" checks.

## Your Environment

* Version used (`icinga2 --version`): r2.10.5-1 and v2.11.0-rc1-56-gfcca9643b
* Operating System and version: Ubuntu 18.04.3 LTS
* Enabled features (`icinga2 feature list`): api checker ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): Irrelevant to the problem at hand
* Config validation (`icinga2 daemon -C`):

(Only the 2.10.5-1, but the other one is okay too):

> [2019-09-05 14:39:35 +0200] information/cli: Icinga application loader (version: r2.10.5-1)
> [2019-09-05 14:39:35 +0200] information/cli: Loading configuration file(s).
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Committing config item(s).
> [2019-09-05 14:39:35 +0200] information/ApiListener: My API identity: A-SRV
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 2 Services.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 2 Hosts.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 1 FileLogger.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 1 ApiListener.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 4 Zones.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 3 Endpoints.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 1 ApiUser.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
> [2019-09-05 14:39:35 +0200] information/ConfigItem: Instantiated 215 CheckCommands.
> [2019-09-05 14:39:35 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
> [2019-09-05 14:39:35 +0200] information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

Sanitized version of /etc/icinga2/zones.conf:

> object Endpoint "A-SRV" {
> }
> object Zone "master" {
>         endpoints = [ "A-SRV" ]
> }
> object Endpoint "B-SRV" {
>         host = "1.2.3.4"
>         port = "5665"
> }
> object Zone "sat" {
>         endpoints = [ "B-SRV" ]
>         parent = "master"
> }
> object Zone "global-templates" {
>         global = true
> }

Additional, sanitized version of config file /etc/icinga2/zones.d/sat/sat.conf
(this is needed in exactly this directory, otherwise the satellite won't know the client):

> object Endpoint "C-SRV" {
>         host = "2.3.4.5"
>         port = "5665"
> }
> object Zone "client" {
>         endpoints = [ "C-SRV" ]
> 	parent = "sat"
> }

## Additional context

This is not a grave issue unless you want to forgo dependencies and the pinging involved with them (which we're attempting to do here). It's just to avoid monitoring personal being overwhelmed by messages on every Windows server reboot, intentional or not. Yes, it's "only" purple messages, not red or yellow ones, but it can still lead to dulling of the senses ("There are always alarms in Icinga, I don't even look at the screen anymore").

I might file a feature-request in the future that zones and endpoints can be used in dependencies, both active and passive. I love the object-model of Icinga2 and like to take full advantage of it in order to avoid the usual problems with firewalls etc. in customer environments.

**Comment by mcktr** [comment]
This is the expected behavior, you are mixing up two configuration modes:

* Config Sync 
* Command Endpoint

**Config Sync**

https://icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#top-down-config-sync

When you are using the config sync mode checks are scheduled on the child's scheduler (e.g. your satellite). That has the consequence that checks are also planned and executed when the connection to the parent (e.g. your master) drops. When the connection is re-established the child will replicate the Replay log to ensure the check history is in sync. 

**Command Endpoint**

https://icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#top-down-command-endpoint

Using the command endpoint mode checks are scheduled on the parent (e.g. your satellite) and executed on the given command endpoint. If the connection now drops the scheduler will continue to schedule checks for the given command endpoint, but the checks won't be executed in time which results then in the check result message: _Remote Icinga instance 'child' is not connected to 'parent'_.

Windows Agents are typically configured via the command endpoint mode.

You can configure a health check for the Windows agents to determine if it is connected or not. Building on the health check you can create a service dependency to pause agent checks like `disk-windows`, `load-windows`, etc. 

https://icinga.com/docs/icinga2/v2.11.0-rc1/doc/06-distributed-monitoring/#health-checks

For further configuration questions I would kindly refer you to the community channels at https://community.icinga.com/

**Comment by dnsmichi** [comment]
I've recently updated the distributed monitoring chapter to include more specific details about dependencies which can prevent such checks and notifications for agent hosts.

https://icinga.com/docs/icinga2/snapshot/doc/06-distributed-monitoring/#cluster-zone-with-masters-satellites-and-agents

Anyhow, since this is the expected behaviour and more of a configuration question, proceed on the community forums. I'll close here.
