### ISSUE TITLE
Loading shared libraries from user directory

### ISSUE THREAD

**Issue by mamiral** [Icinga/icinga2#7488]
## Describe the bug

I'm encountering a strange bug. I'm sorry if this is not appropriate place to post, but i really don't know where to ask.

I am not a decision maker here.
This is a set-up configured by puppet, i'm monitoring multiple processes in a "closed source package" which gets deployed to /home/myuser with all the exe files and shared libs .so objects. The check to monitor these processes was written by myself and it's from the "package" ecosystem, i.e. it needs to load certain .so to work and access process private data and such.

I have added icinga user to myuser group and set /home/myuser rwx rights for groups and I have also updated ld.conf accordingly, to be able to find and load .so files.

The problem:
When icinga starts up on any node (with /home/myuser permissions and ld.conf set and all), it reports that it can't find shared libs. I have restarted icinga service on node and master countless times.
But when I change one of the checks to execute "/usr/bin/ls" with args "/home/myuser", it finds .so files and all other checks start to work.

I'm confused.

Please help.

## To Reproduce

Maybe try to load shared libs for a check from /home/myuser...

## Expected behavior

Expect check to work with access permissions set and ld.conf set.

**Comment by dnsmichi** [comment]
The Icinga daemon cannot load shared libraries into its execution process context. That is for the executed plugins, they need to load such. You can only prepare the environment within the icinga process and user context for those. /etc/sysconfig/icinga2 on RHEL/SLES, /etc/default/icinga2 on Debian allows to specify environment variables, like LD_LIBRARY_PATH overrides.

I'd suggest asking this at https://community.icinga.com since this reaches a broader audience with custom plugins and whatnot.

**Comment by mamiral** [comment]
Ok, thanks. So it's basically a system issue. I just don't get it why it is able to find libs after i do ll into the home dir. I will try to set up the sysconfig.
Thanks again.
