### ISSUE TITLE
Creating timeperiod without permissions returns 503 error

### ISSUE THREAD

**Issue by ricsil** [Icinga/icinga2#7513]
## Describe the bug

When creating a timeperiod via API without permissions for such action, 

````{"error":503.0,"status":"Unhandled exception"}````

is returned. Also, not sure whethers thats also a bug, but as I requested ````pretty=1````, this should have been

````
{
    "error":503.0,
    "status":"Unhandled exception"
}
````

## To Reproduce

````curl -X PUT -H "Accept: application/json" -H "Authorization: Basic XXX" -d '{"attrs": {"display_name": "Test Period", "ranges.monday": "00:00-24:00"}}' 'https://localhost.localdomain:5665/v1/objects/timeperiods/test_period?pretty=1&verbose=1'````

You'll get the following in your log:

````[2019-09-19 15:32:09 +0200] warning/FilterUtility: Missing permission: objects/create/timeperiod````

So it looks like the exception is handled! 

## Expected behavior

HTTP error specifying that this is a permissions issue.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.10.4
* Operating System and version: RHEL7

**Comment by dnsmichi** [comment]
Should result in a 404. Telling the user that this is a permission issue opens an attack vector for guessing and trying things. We'll look into that.

**Comment by ricsil** [comment]
Could you get into more details about this? We were wondering about this choice before too - why Icinga2 chose to return 404 in such cases? It's returned when user doesn't have permissions to delete and object, update status of an object, etc., but we saw it as a bit confusing, especially once you know that object exists :D

**Comment by dnsmichi** [comment]
Imagine that someone has hijacked your session or knows the basic auth credentials. Now there's a list of URL endpoints one can extract from the docs or source code, or just use simple plain word guessing. Whenever we would return "permission error" instead of "not found", the attacker can guess all URL endpoints and in addition, the object names part of the URL.

So without any permission, you can easily collect a list of object names with just guessing them from character lists and dictionary words. Whenever Icinga returns "permission error", you collect this URL into your result set. At the end you have a list of available object names without having permissions at all.

Keep in mind that object names also contain sensitive details about your company environment. Host object names typically follow patterns, or use the FQDN. That's something scripts and tooling may guess in seconds, minutes, hours. With the increased CPU resources these days, such guessing brute force attacks are very common.

Other tools like GitHub or GitLab do the same - if you ain't got permission to see the repository, you get a generic 404 error.

**Comment by dnsmichi** [comment]
The code just uses a generic 503 error in this case, this has been sitting there since the very beginning and includes any other problem thrown in the http handlers. So not really an issue from security POV here, since guessing from remote isn't possible.

**Comment by dnsmichi** [comment]
Not yet satisfied with it, but it could look like this: 
![Screen Shot 2019-09-20 at 13 04 39](https://user-images.githubusercontent.com/382049/65322501-585caa00-dba7-11e9-87ca-94b3c8908538.png)
