### ISSUE TITLE
Get a list of templates via CLI

### ISSUE THREAD

**Issue by ricsil** [Icinga/icinga2#7520]
## Is your feature request related to a problem? Please describe.

You can use

 ````icinga2 object list --type TYPE```` 

to get list of objects of specific type.

Recently I wanted to find all notification templates we have, and those apparently are not objects. To work around that, you can use<sup>[0]</sup> and then grep for usage of that object name<sup>[1]</sup>  to find that the template you need is also called "mail-service-notification", but this doesn't have to be 1:1 mapping, which complicates things :(

[0]
````
/etc/icinga2/ # icinga2 object list --type NotificationCommand | grep Object
...
Object 'mail-host-notification' of type 'NotificationCommand':
Object 'mail-service-notification' of type 'NotificationCommand':
...
```` 

[1]
````
/etc/icinga2/ # grep -R 'command = "mail-service-notification"' -B 1
...
zones.d/global-templates/templates.conf:template Notification "mail-service-notification" {
zones.d/global-templates/templates.conf:  command = "mail-service-notification"
...
````

## Describe the solution you'd like

From my POV, either template has to be an object that can be listed via the same command, or another command, namely

````# icinga2 template list````

is required. Or the solution here is to always name your templates the same way you name your NotificationCommand?

## Environment

If this part is relevant, we're still on 2.10.4, RHEL7

**Comment by dnsmichi** [comment]
We encourage users to use `/v1/templates` via the REST API for this, instead of creating yet another CLI command. `object list` solely serves the purpose of printing the configuration object attribute tree with additional debug info, next to the obvious object names.

Technically, templates never reach the config objects. They exist as compiled AST in memory with only their name in a raw string, allowing you to incorporate them in API PUT requests for example. Still, you cannot access their attributes as known from config objects.

**Comment by ricsil** [comment]
Thanks, was not aware of ```/v1/templates``` endpoint. Implemented in our tooling, cheers!
