### ISSUE TITLE
node wizard has no support for existing TLS certificate

### ISSUE THREAD

**Issue by flaminggenius** [Icinga/icinga2#7619]
## Describe the bug

If a TLS self-signed certificate already exist then the wizard will fail with 
critical/cli: Failed to create new self-signed certificate for CN 'xxx.xxx.xxx.xxx'. Please try again.

## To Reproduce

1. Create a new bare minimum centos
2. Create a TLS self-signed certificate
3. Run icinga2 node wizard

## Expected behavior

There should be an option to use an existing certificate. My company is trying to setup monitoring on our phone servers and the phones use a TLS certificate thatss on the server so we can't just create a new one we need the option to use the one that already exists.

**Comment by flaminggenius** [comment]
Also if anyone knows of some documentation where I can go through the steps manually that would be great

**Comment by dnsmichi** [comment]
The CLI wizards are not designed for re-using existing certificates, they are made for helping users without TLS certificate knowledge. Also, they create certificates including required extensions. One of them is the subject setting the CN to the FQDN, which is a requirement for implementing a distributed environment. 

In terms of trust, I strongly recommend to use the Icinga CA and not integrated the monitoring instances into a different layer and CA. 

Also, with using the CLI helpers you can build things like CSR auto-signing or on-demand signing where the whole certificate building is abstracted and trusted.

In case you really want to go the route with own certificates, you can inspect the source code how it is done. We don't provide documentation for that, since custom certificates always expose errors no-one expects. You can learn more about this [here](https://community.icinga.com/t/own-ca-for-icinga-cluster-api-communication/243).
