### ISSUE TITLE
Config check for staged config

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#7658]
Hi,

When the combination of local config and synced config will render an invalid configuration, the staging mechanism introduced with Icinga 2 2.11 will prohibit a reload of Icinga 2 which is great.

My problem is, all I'm seeing in the Satellites log is this:

```
information/ApiListener: Received configuration updates (2) from endpoint 'master01.example.com' do not qualify for production, not triggering reload.
```

What I would like to have is a hint what actually went wrong. I could live with having this information in a logfile but I would really appreciate it if I could have something like:

```
icinga2 daemon -C --stage
```

I know, I can give an alternative configuration file but as it looks to me, I'm not able to build the same configuration that the staging mechanism is using for testing.

Cheers,
Thomas

**Comment by widhalmt** [comment]
ref/NC/650835

**Comment by dnsmichi** [comment]
When you see this log line, the configuration never reaches any stage validation at all. This is part of the cluster receive and checksum comparison logic, and as such, the checksums are equal, timestamp passes and therefore no additional change or reload is needed. Otherwise the endpoint would reload every time it receives config.

Some log lines above it tells you that it will be checking the checksums for the zone config sync.

If you are looking for errors from a real config validation from the staged config content, that's logged differently, including a path to the log file. As always, this can be read here: https://icinga.com/docs/icinga2/latest/doc/19-technical-concepts/#config-sync-receive-config

**Comment by widhalmt** [comment]
Ok, then the logmessage was misleading, at least for me. "do not qualify for production" sounds more like broken config to me. What you describe could lead to a logline like "freshly synced configuration did not change, not triggering config check and reload". I'm sorry, but I didn't find this exact logmessage in the docs.

I'll have a second look at the current problem, it seems like there should be a verification log / `startup.log` showing the errors. The strange thing is, though, that neither the customer who reported an issue nor I in my personal infrastructure could find the startup.log . I'll be investigating and then come back. Thanks for your help so far.

**Comment by dnsmichi** [comment]
I'm open for changing the log line once more. I already did that for 2.11.2 but it seems one cannot find the right term for that.

**Comment by Wintermute2k6** [comment]
Just to add some facts, after resolving the sync issue i found out that the staging files were the fault because they had a re-define inside of them which .. i don't know why synced successfully to the second master.

So the whole setup couldn't receive new config from the master ... 

The initial try from the customer was to create a new satellite ha pair

**Comment by dnsmichi** [comment]
To summarize this issue:

- If the received configuration is equal, or older than the deployed one, no config validation/reload is triggered
- Whenever the staged configuration has been validated, access to the `status.log` is granted and one can use this for troubleshooting. 
- The log message with `does not qualify for production` require a change, I will do so in a separate PR.

That being said, I'll close here.
