### ISSUE TITLE
OpenTSDB / Custom Tag / empty string => failure

### ISSUE THREAD

**Issue by handfreezer** [Icinga/icinga2#7724]
For the end, I have compiled Icinga2 to get a preview of custom tag with OpenTSDB and I got a problem : with default config file and  by activating default custom tag zone : I have a failure in opentsdb 2.3 as tag 'zone=' is an invalid tag  : I guess it is because the string is empty.

So, I guess there is a choice to be done : do we set custom empty tag with an empty string or do we remove empty tag from perfdata inserted into opentsdb?

@Ant1x : any point of view?

Best regards
related to commit 3cd6b66cd430a4f080a6aeabca5b9e4ef2ac21ca

First message:
Hello,

   I saw that there was a commit for managing tags in perfdata for opentsdb.
   Is there a place about the roadmap for next release?

Best regards

**Comment by Ant1x** [comment]
Hello @handfreezer 
Good catch, the zone in your Icinga Host/Service configuration may have an empty value which explains the behaviour you are seeing.

If you'd like to check out the functionality I'd suggest using `checkcommand` as below, since this is a required attribute on each Host and Service object, whereas zone is an optional attribute.

I wonder if it's worth changing the example configuration file to match what I have written in the docs, which is using `checkcommand = "$host.check_command$"` and `checkcommand = "$service.check_command$"` instead of `zone = "$host.zone$"` etc.
More examples can be found here: https://github.com/Icinga/icinga2/blob/master/doc/14-features.md#custom-tags-


I think the only valid option for an improvement here is to skip over tags with empty values, therefore not sending the tag in question at all to OpenTSDB. According to these references, OpenTSDB isn't meant to receive any blank values in the key/value pair:
https://groups.google.com/forum/#!topic/opentsdb/kVsrnuXMDCg
https://github.com/OpenTSDB/opentsdb/issues/412
If it does, it will reject it anyway.

Hope that helps!

**Comment by handfreezer** [comment]
Hello,

  I fully agree with your analyze : I have no zone set, this is the root cause.
  It is also showing that a common case might happen : the result of a calculated macro could be an empty string.

  To checkout the functionnality, I created a nested tag named "host_test" with the macro "$host.displayname$" ;-)

  And at the end, I also agree with you : if the final value of a tag is empty or "null", it should be skiped.

  I have clone the git repo of icinga2 localy to my test server, but not forked it in github. Should I have to do so to make the change? or may I make the change now locally and then try to push? (ok I never used git with github, and so don't know the right process).

**Comment by handfreezer** [comment]
(just in case you're interested in, I also opened  #7729, just to get at least your point of view...)

**Comment by handfreezer** [comment]
Hello,

  I'm not used to use github, and so, i would like to know what the process is to suggest a modification. Should I have to ask for a specific branch here, or should I have to fork on my account first?

**Comment by dnsmichi** [comment]
Follow the instructions here please: https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md

**Comment by dnsmichi** [comment]
@handfreezer You can try to adopt the code from the current influxdbwriter parts, https://github.com/Icinga/icinga2/blob/master/lib/perfdata/influxdbwriter.cpp#L255

**Comment by Al2Klimov** [comment]
Hello @handfreezer and @Ant1x and thank you for reporting!

Please could you test #7928?

Best,
AK

**Comment by Ant1x** [comment]
@Al2Klimov So far that looks good to me, I'll try and get this deployed in our testing environment over the next week or so and report back

**Comment by Al2Klimov** [comment]
PING @Ant1x
