### ISSUE TITLE
Conflict when install nagios-plugins-all on centOS 8

### ISSUE THREAD

**Issue by marinovgit** [Icinga/icinga2#7927]
## Describe the bug
There is installed MariaDB-common-10.4.12-1.el8.x86_64 from the MariaDB repo which conflicts with mysql-common-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 when try to install nagios-plugins-all.

*edit
the problematic package is nagios-plugins-mysql

CentOS Linux release 8.1.1911 (Core)
nagios-plugins-all x86_64  2.2.2-2.20190926git1b8ad57.el8

## To Reproduce
Install these before nagios-plugins-all:
MariaDB-client-10.4.12-1.el8.x86_64
MariaDB-server-10.4.12-1.el8.x86_64
MariaDB-common-10.4.12-1.el8.x86_64

Error:
```
Error: Transaction check error:
  file /usr/share/mysql/charsets/Index.xml from install of mysql-common-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 conflicts with file from package MariaDB-common-10.4.12-1.el8.x86_64

```

Solution
`dnf install icinga2 nagios-plugins-* vim-icinga2  --exclude=nagios-plugins-mysql --exclude=nagios-plugins-all`

**Comment by Al2Klimov** [comment]
@N-o-X Shall we document this workaround?

**Comment by Mikesch-mp** [comment]
Same problem if you install icinga2-ido-mysql. you cant install it when you have MariaDB installed :( only works with MySQL8, though you get MariaDB from from RHEL/Centos base repo.

**Comment by sanddweller** [comment]
Same issue when mysql-community version 5.7 is installed.

I'd have preferred to use mysql8, but using AWS/Aurora, whichis currently max v5.7, and need matching mysql cli and mysqldump, etc.
Thanks @marinovgit for the answer! :)

**Comment by magicdrums** [comment]
I don't know if it's the same but I think you have to enable the Powertools repos in Centos 8 so that the dependencies are resolved correctly ... I found it here https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F

**Comment by tlo8640** [comment]
starting with rpm 4.13 there should be "OR" possible in the requires line in the spec file:
http://rpm.org/user_doc/boolean_dependencies.html
there you can specify 
`Requires: (mysql-common or MariaDB-common)`
If icinga2-ido-mysql is packaged with this line in spec file it could solve the problem
for the nagios plugins (monitoring-plugins) someone should report this to the packager of distro
if you package you have to package with this rpm version, ottherwise build will fail, because the rpm Version does not know this syntax (e.g. Building for rhel8 with rhel7 will fail: https://github.com/rpm-software-management/mock/wiki/FAQ)
Unfortunately I didn't tested it, so it's only afaik...

**Comment by philfry** [comment]
Hi all,

since EL8 all relevant packages are compiled against `mariadb-connector-c`, not `mysql` (except for `mysql-common`, obviously):
```
$ dnf repoquery --whatrequires 'libmariadb.so.3()(64bit)' --qf '%{reponame} %{name}' | \
  awk '{x[$1]++} END{for(y in x){print x[y],y}}'
35 epel
18 ol8_appstream

$ dnf repoquery --whatrequires 'libmysqlclient.so.21()(64bit)' --qf '%{reponame} %{name}' | \
  awk '{x[$1]++} END{for(y in x){print x[y],y}}'
19 epel
1 ol8_appstream
1 icinga-stable-release

$ dnf repoquery --whatrequires 'libmysqlclient.so.21()(64bit)' --qf '{name}'
icinga2-ido-mysql

$ dnf whatprovides 'libmysqlclient.so.21()(64bit)'
mysql-libs-8.0.13-1.module+el8+5199+1dce7bb2.x86_64 : The shared libraries required for MySQL clients
Repo        : ol8_appstream
Matched from:
Provide    : libmysqlclient.so.21()(64bit)
```
Unfortunately, MariaDB is not willing to provide libmysqllient.so.21 in the `MariaDB-compat` package.

So IMHO the icinga2-packages should be recompiled against `mariadb-connector-c` to match the distribution standards (?) and to allow the concurrent installation of icinga2-ido-mysql and MariaDB 10.x.

**Comment by htriem** [comment]
The revisions 2.11.10-2 and 2.12.5-2 are now being built against mariadb-connector-c (see: Icinga/icinga-packaging#205). Would anyone please check if the problem persists with these versions or if this has been fixed?

**Comment by N-o-X** [comment]
I'll close this issue here, since there's no further feedback or indication that this is still an issue. Feel free to reopen this if you still encounter this problem.
