### ISSUE TITLE
SLES 11 SP4 repository is broken (requires libcrypto.so.1.0.0()(64bit))

### ISSUE THREAD

**Issue by sjvudp** [Icinga/icinga2#7982]
## Describe the bug

Trying to user the SLES-11.4 repository, I realized that there is an unresolvable dependency, requiring "libcrypto.so.1.0.0()(64bit)".

## To Reproduce

On SLES 11 SP4 using the 11.4 repository, select to install icinga-bin

## Expected behavior

The package and dependencies should be installed.

## Your Environment

* Version used (`icinga2 --version`): icinga-bin-2.10.4-1.icinga.x86_64
* Operating System and version: SLES 11 SP4

**Comment by Al2Klimov** [comment]
*bump*

**Comment by lazyfrosch** [comment]
SLES 11 is no longer a supported release, since the normal support by SUSE ended and it is longtime support only. https://www.suse.com/lifecycle

But still, you are missing the "SLES 11 Security Module": https://www.suse.com/c/introducing-the-suse-linux-enterprise-11-security-module/

> The packages for SLES 11 depend on the openssl1 package which is distributed as part of the SLES 11 Security Module.

https://github.com/Icinga/icinga2/blob/v2.10.4/doc/02-getting-started.md#sles-security-repository-
