### ISSUE TITLE
Forget that attribute is modified if it's changed back to its original state via API

### ISSUE THREAD

**Issue by lippserd** [Icinga/icinga2#7986]
When changing object attributes like `enable_active_checks` via Web's command feature toggles or directly via the API, Icinga remembers this value and stores it to `/var/lib/icinga2/modified-attributes.conf`. Upon configuration reloads, this file overrides any previous configuration.

Even if you change the attribute back to its original state, it counts as modified.

Imagine the following situation:

* Host has active checks enabled
* Disable active checks via the frontend to test something
* Enable active checks
* Change the configuration of the host to have active checks disabled because you have a new check mechanism and propagate check results passively now
* Reload Icinga
* Notice that active checks are still enabled

Further this file "grows" for every temporary change of an object.

I think we should just simply drop the modified attribute entry if it matches the current configuration.

Please also see:

- https://lists.icinga.org/pipermail/icinga-users/2016-July/011240.html
- https://github.com/Icinga/icingaweb2/issues/4071

**Comment by abaumgaertner** [comment]
Similar Topics #8036 #8709

**Comment by abaumgaertner** [comment]
It would be great to query for modified attributes.
Maybe an additional structure that lists the modified attributes and idealy the inital config value.

1.    Complex custom vars (.e.g json strings or "_override_servicevars" ) would need exact matching to be "forgotten" / reset. And there is no way to know that the reset worked from standard api call.
 2.   Proposes an implicit functionality. the provided example would suggest that a config change of the intial value from Linux to Ubuntu triggers all custom vars that were explicitly set to Ubuntu via API would be reset due to now matching value of custom var and config. After a template change back from Linux to Ubuntu, this would cause the explicitly set Ubuntu Variables now automatically changed back to Linux. There will be headscratching down this road ...

A call to explicitly reset attributes seems a controlled way.
curl -k -v -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/objects/hosts/resetattributes/example.localdomain' -d '{"attrs": {"vars.os": null, "enable_notifications": null, , "vars.dummyarray": [], "_override_servicevars": null}, "pretty": true}'

curl -k -v -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/objects/services/resetattributes/example.localdomain' -d '{"attrs": {"vars.os": null, "enable_notifications": null, , "vars.dummy array": [], "_override_servicevars": null}, "pretty": true}'

curl -k -v -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/objects/hosts/resetattributes -d '{ "filter": "match(\"OpenStack\",host.groups, MatchAny)", "pretty": true, "attrs": { "enable_notifications": null, "vars.dummy array": [] } }'

All attributes passed would be reset to default values, irrespective of the passed value. Maybe not the most consistent ( you have to specify a value for a json variable ) approach but would work nice with filter and current implementation.

or

curl -k -v -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/objects/hosts/resetattributes/example.localdomain/enable_notifications'
curl -k -v -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/objects/hosts/resetattributes/example.localdomain/vars.os'
curl -k -v -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/objects/hosts/resetattributes/example.localdomain/vars.dummy%20array'

**Comment by Al2Klimov** [comment]
ref/IP/43160

**Comment by julianbrost** [comment]
> It would be great to query for modified attributes.

There is an object attribute called `original_attributes`, everything in there is modified. It also gives the value you'd have to send to reset it with what is suggested in this issue and implemented by #8036.

> 2\. Proposes an implicit functionality. the provided example would suggest that a config change of the intial value from Linux to Ubuntu triggers all custom vars that were explicitly set to Ubuntu via API would be reset due to now matching value of custom var and config. After a template change back from Linux to Ubuntu, this would cause the explicitly set Ubuntu Variables now automatically changed back to Linux. There will be headscratching down this road ...

I'm not sure if I don't understand or if there is some confusion with what was proposed in #8717 and #8739. The override would only be cleared if there is an explicit API call setting the same value that's currently in the config file. The override should continue to exist if the value in the config file is changed to the value from the override and it should only be cleared if you do an API request setting the same value again.
