### ISSUE TITLE
The host list page cannot find the host created through the API

### ISSUE THREAD

**Issue by lwenbin** [Icinga/icinga2#9051]
hi,
   This is the command to create the host
![image](https://user-images.githubusercontent.com/24451113/139256385-1f3d23dc-98b7-4f16-af46-8b955aa0b6eb.png)
And it can be queried through the interface
![image](https://user-images.githubusercontent.com/24451113/139256529-92db8ade-3f1e-4198-bb6d-1beca846a1f8.png)
However, it cannot be queried through the host list page
![image](https://user-images.githubusercontent.com/24451113/139256777-aca24971-cb5a-4b01-9a5a-0736daafe063.png)
please help me ,thanks

**Comment by julianbrost** [comment]
There seems to be some confusion about APIs provided by different parts of the Icinga stack. Both Icinga 2 (sometimes also referred to as "core") and Director provide their own APIs. For API-created objects to show up in Director, you have to create these using the [Director API](https://icinga.com/docs/icinga-director/latest/doc/70-REST-API/) so that the Director will then deploy these objects to Icinga 2.
