### ISSUE TITLE
Changing scheduled downtimes in Icinga Web in any way causes duplication

### ISSUE THREAD

**Issue by Nayakum** [Icinga/icinga2#9142]
## Expected Behavior
When I change a scheduled downtime in Icinga Web, the current scheduled downtime should be changed accordingly and no other actions should take place. So for example, when I change the comment of a scheduled downtime to document my changes, said comment is all that should happen. 

## Current Behavior
When I change one of the following aspects of a scheduled downtime, a new scheduled downtime is applied to the hosts instead of changing the current one. In "Icinga Director --> Scheduled Downtimes", only one configured scheduled downtime is visible, it being the one with the most recent changes. The /zones.d/master/scheduled_downtime_apply.conf also only shows the most recent scheduled downtime.

 - Comment
 - Range
 - Author
 - Fixed to flexible (changing back does not create additional downtimes)
 - Flexible to fixed (changing back does not create additional downtimes)
 - Duration (doesn't matter if the the downtime is fixed or flexible)

"Overview --> Downtimes" after changing some of the stuff:
![grafik](https://user-images.githubusercontent.com/84782250/144197720-be3bfd3a-1571-46c2-8fb8-f7ef10762c29.png)

"Icinga Director --> Scheduled Downtimes" afterwards:
![grafik](https://user-images.githubusercontent.com/84782250/144197835-554cf397-f416-426b-a261-0b634566a27d.png)

/zones.d/master/scheduled_downtime_apply.conf:
![grafik](https://user-images.githubusercontent.com/84782250/144197929-38f4baed-2300-486d-a8ed-f2cf57338f98.png)

Changing the name of the scheduled downtime does not create additional downtimes, but removes all other wrongly created additional downtimes which were created in between.

## Steps to Reproduce (for bugs)
Create a downtime, deploy, and change one of the attributes mentioned above, and deploy again.

## Your Environment

* Director version (System - About): 1.8.1
* Icinga Web 2 version and modules (System - About): 
![grafik](https://user-images.githubusercontent.com/84782250/144192580-4c13c758-f527-4e01-a68f-2719da0db3cf.png)

* Icinga 2 version (`icinga2 --version`): version: r2.13.1-1
* Operating System and version:  SUSE Linux Enterprise Server 15 SP1

**Comment by tbauriedel** [comment]
ref/NC/740852

**Comment by Al2Klimov** [comment]
I consider this behaviour (#8310) reasonable. And you, colleagues?

**Comment by julianbrost** [comment]
Works as [intended with the last change to the behavior](https://github.com/Icinga/icinga2/pull/8310#issuecomment-874844767). The idea there was to not touch already started downtimes, so given that your config snippet has `"wednesday" = "10:00-11:00"`, that test was probably done in this time, otherwise, the already created downtimes should have been all in the future and then replaced completely.

Part of the reason for that is how downtimes aren't intended to be modified, so for example you can't change the end of a downtime (expect by completely removing it), which is basically what would be necessary to apply changes from a scheduled downtime to an active downtime.

IMHO randomly changing the behavior with every release doesn't really help anyone, so I would only change this if there's a practical suggestion that's an improvement over the current behavior in general.
