### ISSUE TITLE
Performance data is not visualized, if the perfdata is not only in a single line of the check result

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icinga2#9379]
## Describe the bug
If a check result contains multiple lines with performance data, only to first one is show inside Icingaweb2, although, to my understanding, [the Monitoring Plugins guidelines](https://www.monitoring-plugins.org/doc/guidelines.html#AEN201) suggest otherwise and Icinga2 also process those correctly.

## To Reproduce
Use something like this:
```
WARNING - states: warning=1 ok=2
[WARNING] Dual Humidity Port 1: 43% | 'Dual Humidity Port 1'=43%
[OK] Dual Temperature Port 1: 26C | 'Dual Temperature Port 1'=26c
[OK] Temp Sensor Test: 21C | 'Temp Sensor Test'=21c
```
as a check result.

## Expected behavior
Performance data should be taken from all lines in the check result

**Comment by Al2Klimov** [comment]
Fixed with 2.13.8 by:

* #9821

## Before

![Bildschirmfoto 2023-09-07 um 17 53 52](https://github.com/Icinga/icinga2/assets/6053266/5b83d392-6376-405c-8347-6b841a077fac)

## After

![Bildschirmfoto 2023-09-07 um 17 57 25](https://github.com/Icinga/icinga2/assets/6053266/b7b55e6d-551e-4d56-babb-327b7e208583)
