### ISSUE TITLE
Unable to modify MaxConcurrentChecks on 2.14

### ISSUE THREAD

**Issue by yoshi314** [Icinga/icinga2#9836]
``` 
[2023-07-17 21:09:00 +0200] critical/config: Error: Namespace is read-only and must not be modified.
Location: in /etc/icinga2/features-enabled/checker.conf: 6:3-6:27
/etc/icinga2/features-enabled/checker.conf(4): 
/etc/icinga2/features-enabled/checker.conf(5): object CheckerComponent "checker" {
/etc/icinga2/features-enabled/checker.conf(6):   MaxConcurrentChecks = 256
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/features-enabled/checker.conf(7): }
/etc/icinga2/features-enabled/checker.conf(8): 
```

## To Reproduce

``` 
features-enabled/checker.conf

object CheckerComponent "checker" { 
  MaxConcurrentChecks = 256 // or anything else
}
```

## Expected behavior

It works

## Your Environment

icinga2-2.14.0-1+debian10 on debian 10, from packages.icinga.com repository.

If any further info is necessary, i'll provide it.

**Comment by log1-c** [comment]
Can confirm.
Single master system with IDO on Ubuntu 20.04.

**Comment by julianbrost** [comment]
The `concurrent_checks` attribute of `CheckerComponent` [was moved](https://icinga.com/docs/icinga-2/latest/doc/16-upgrading-icinga-2/#configuration) to a global constant `MaxConcurrentChecks` but you're still setting it like it was an attribute of `CheckerComponent`.

Now this kind of worked before because assigning to a name that's not an attribute inside an object falls back to setting a global variable, which already resulted in a warning before:

> [2023-07-24 09:07:34 +0000] warning/config: Global variable 'MaxConcurrentChecks' has been set implicitly via 'MaxConcurrentChecks = ...' in /tmp/i2.conf: 2:2-2:26. Please set it explicitly via 'globals.MaxConcurrentChecks = ...' instead.

Now that's typically not what you'd want and Icinga 2.14 is more restrictive regarding setting global variables.

Instead, please set `MaxConcurrentChecks` in `constants.conf` as it's intended to be used.
