### ISSUE TITLE
Icinga2 on Raspbian OS Dependencies Error

### ISSUE THREAD

**Issue by Saibot97** [Icinga/icinga2#9846]
Hey everyone,

I wanted to install Icinga2 on a Raspberry Pi using Raspbian OS (64bit,CLI).
I followed the Icinga Documentation under: https://icinga.com/docs/icinga-2/latest/doc/02-installation/03-Raspbian/
When i try to install Icinga2 using `apt install icinga2` i get the following error:

`root@testicinga:/home/admin# apt install icinga2`
`Paketlisten werden gelesen… Fertig`
`Abhängigkeitsbaum wird aufgebaut… Fertig`
`Statusinformationen werden eingelesen… Fertig`
`Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass`
`Sie eine unmögliche Situation angefordert haben oder, wenn Sie die`
`Unstable-Distribution verwenden, dass einige erforderliche Pakete noch`
`nicht erstellt wurden oder Incoming noch nicht verlassen haben.`
`Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:`
`Die folgenden Pakete haben unerfüllte Abhängigkeiten:`
 `icinga2 : Hängt ab von: icinga2-bin (= 2.12.3-1) soll aber nicht installiert werden`
          ` Hängt ab von: icinga2-common (= 2.12.3-1) aber 2.14.0-1+raspbian11 soll installiert werden`
           `Empfiehlt: icinga2-doc (= 2.12.3-1) soll aber nicht installiert werden`
           `Empfiehlt: monitoring-plugins-basic soll aber nicht installiert werden oder`
           `           nagios-plugins-basic`
           `Empfiehlt: libreadline7 ist aber nicht installierbar`
`E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.`

My Icinga.list:

`root@testicinga:/home/admin# nano /etc/apt/sources.list.d/icinga.list`

`deb [signed-by=/usr/share/keyrings/icinga-archive-keyring.gpg] https://packages.icinga.com/raspbian icinga-bullseye main`
`deb-src [signed-by=/usr/share/keyrings/icinga-archive-keyring.gpg] https://packages.icinga.com/raspbian icinga-bullseye main`

**Comment by julianbrost** [comment]
Raspbian/Raspberry Pi OS is a bit chaotic. The 32 bit version is basically it's own distribution that's incompatible with Debian whereas the 64 bit version is just Debian with a few extra packages. Therefore, please try following the instructions for Debian (basically use https://packages.icinga.com/debian instead of https://packages.icinga.com/raspbian).

**Comment by 4NESTobi** [comment]
That wouldnt work, because of the architecture or ?
The Pis are arm64.

**Comment by julianbrost** [comment]
We've started uploading arm64 packages for Debian: https://packages.icinga.com/debian/dists/icinga-bullseye/main/binary-arm64/

So far it's still a bit experimental as we haven't uploaded all packages for that architecture yet, but Icinga 2 is in that repo.

**Comment by 4NESTobi** [comment]
Okay, well i need to install a testsetup of an Icinga Evironment(icinga, Icingaweb, director, Jira, Cube)
and i only got an raspberry pi 4 for that.
Can i do that on the raspberry with one of the repos ?

**Comment by Al2Klimov** [comment]
@bobapple What about adding https://packages.icinga.com/raspbian64/ as e.g. symlink to https://packages.icinga.com/debian/ so that users follow the correct instructions?

**Comment by Al2Klimov** [comment]
> Okay, well i need to install a testsetup of an Icinga Evironment(icinga, Icingaweb, director, Jira, Cube)
> and i only got an raspberry pi 4 for that.
> Can i do that on the raspberry with one of the repos ?

Meanwhile we've releases new versions of a lot of modules along with ARM64 packages, so you should be able to assemble a test setup with the Debian repo.

**Comment by bobapple** [comment]
Not sure why this issue was assigned to me, but here are my two cents:
I'm in favour of updating the docs instead of creating symlinks. Since there are multiple versions of Raspbian that require different repositories, I would suggest to use a similar way like we do for RHEL (7, 8 or later): https://icinga.com/docs/icinga-2/latest/doc/02-installation/06-RHEL/

Each Raspbian version could get it's own small "section" with instructions about which repository should be used.
